Repository CBATeam/CBA_A3, pull requests merged in 2018-06, with the labels that each got.

#935 delete obsolete line
  addons/help/fnc_setCreditsLine.sqf
Labels: Cleanup

#936 Add units[] array to CfgPatches entries
  addons/accessory/MRT_AccFncs/config.cpp
  addons/jr/asdg_jointmuzzles/config.cpp
  addons/jr/asdg_jointrails/config.cpp
  addons/ui/ui_helper/config.cpp
  addons/xeh/CBA_Extended_EventHandlers/config.cpp
  addons/xeh/Extended_EventHandlers/config.cpp
  addons/xeh/ee/config.cpp
  addons/xeh/xeh_a3/config.cpp
Labels: Bug Fix

#941 Cleanup private ARRAY
  addons/accessory/fnc_switchAttachment.sqf
  addons/ai/fnc_addWaypoint.sqf
  addons/arrays/fnc_getArrayDiff.sqf
  addons/arrays/fnc_getArrayElements.sqf
  addons/common/XEH_postInit.sqf
  addons/common/fnc_createMarker.sqf
  addons/common/fnc_getAnimType.sqf
  addons/common/fnc_getArg.sqf
  addons/common/fnc_getAspectRatio.sqf
  addons/common/fnc_getConfigEntry.sqf
  addons/common/fnc_getFov.sqf
  addons/common/fnc_getTerrainProfile.sqf
  addons/common/fnc_getUISize.sqf
  addons/common/fnc_getUnitAnim.sqf
  addons/common/fnc_getUnitDeathAnim.sqf
  addons/common/fnc_isTurnedOut.sqf
  addons/common/fnc_mapGridToPos.sqf
  addons/common/fnc_mapRelPos.sqf
  addons/common/fnc_modelHeadDir.sqf
  addons/common/fnc_northingReversed.sqf
  addons/common/fnc_objectRandom.sqf
  addons/common/fnc_switchPlayer.sqf
  addons/common/init_delayLess.sqf
  addons/diagnostic/XEH_preInit.sqf
  addons/help/XEH_preClientInit.sqf
  addons/strings/fnc_formatElapsedTime.sqf
  addons/strings/fnc_split.sqf
  addons/ui/flexiMenu/fnc_add.sqf
  addons/ui/flexiMenu/fnc_execute.sqf
  addons/ui/flexiMenu/fnc_getMenuDef.sqf
  addons/ui/flexiMenu/fnc_getMenuOption.sqf
  addons/ui/flexiMenu/fnc_highlightCaretKey.sqf
  addons/ui/flexiMenu/fnc_keyDown.sqf
  addons/ui/flexiMenu/fnc_keyUp.sqf
  addons/ui/flexiMenu/fnc_list.sqf
  addons/ui/flexiMenu/fnc_menuShortcut.sqf
  addons/ui/flexiMenu/fnc_openMenuByDef.sqf
  addons/ui/flexiMenu/fnc_remove.sqf
  addons/ui/fnc_progressBar.sqf
  addons/vectors/fnc_vectCross.sqf
  addons/versioning/XEH_postInit.sqf
  addons/versioning/XEH_preInit.sqf
  addons/versioning/fnc_version_check.sqf
  addons/xeh/fnc_init.sqf
  addons/xeh/fnc_initDisplay.sqf
Labels: Cleanup

#942 Chinese Update
  addons/ui/stringtable.xml
Labels: Translation

#939 Add basic functions for change of basis in 3D
  addons/vectors/CfgFunctions.hpp
  addons/vectors/fnc_matrixProduct3D.sqf
  addons/vectors/fnc_matrixTranspose.sqf
  addons/vectors/fnc_vectMap3D.sqf
  addons/vectors/test_vectors.sqf
Labels: Feature

#940 FIX: CBA_fnc_deleteEntity looping over network and kill dedicated server
  addons/common/fnc_deleteEntity.sqf
Labels: Bug Fix

#945 fix resetting mission settings
  addons/settings/fnc_initDisplayGameOptions.sqf
Labels: Bug Fix

#944 move ui functions to ui component, simplify
  addons/common/CfgFunctions.hpp
  addons/common/fnc_getAspectRatio.sqf
  addons/common/fnc_getFov.sqf
  addons/common/fnc_getUISize.sqf
  addons/ui/CfgFunctions.hpp
  addons/ui/fnc_getAspectRatio.sqf
  addons/ui/fnc_getFov.sqf
  addons/ui/fnc_getUISize.sqf
Labels: Enhancement
