Repository CBATeam/CBA_A3, pull requests merged in 2018-05, with the labels that each got.

#918 French Translation
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/help/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
Labels: Translation

#922 Fix uniqueUnitItems typo and add assignedItems switch
  addons/common/fnc_uniqueUnitItems.sqf
Labels: Bug Fix, Enhancement

#926 formatting uniqueItems header
  addons/common/fnc_uniqueUnitItems.sqf
Labels: Enhancement

#927 remove semi-colon causing script error on preStart
  addons/help/XEH_preStart.sqf
Labels: Bug Fix

#929 Jam
  addons/jam/CfgWeapons.hpp
  addons/jam/config.cpp
  addons/jam/script_macros.hpp
  addons/jam/stringtable.xml
Labels: Enhancement
