Repository CBATeam/CBA_A3, pull requests merged in 2018-04, with the labels that each got.

#901 Add xeh compat for 1.82 (tanks dlc)
  addons/main/script_mod.hpp
  addons/xeh/CfgVehicles.hpp
Labels: Bug Fix

#892 Settings whitelist
  addons/settings/XEH_PREP.sqf
  addons/settings/fnc_whitelisted.sqf
  addons/settings/script_component.hpp
Labels: Feature

#899 Add FILE_EXISTS macro to common macros
  addons/main/script_macros_common.hpp
  addons/settings/fnc_initDisplay3DEN.sqf
  addons/settings/fnc_initDisplayGameOptions.sqf
  addons/settings/fnc_initDisplayMain.sqf
Labels: Feature

#904 Update JR for 1.82
  addons/jr/cfgweapons.hpp
  addons/jr/config.cpp
  addons/jr_prep/config.cpp
Labels: Enhancement

#913 fix script error from whitelist
  addons/settings/fnc_whitelisted.sqf
Labels: Bug Fix

#909 Settings - Fix mouse scrolling on sub categories
  addons/settings/gui.hpp
Labels: Bug Fix

#912 add CBA_fnc_progressBar
  addons/ui/CfgFunctions.hpp
  addons/ui/CfgUIGrids.hpp
  addons/ui/RscTitles.hpp
  addons/ui/XEH_preClientInit.sqf
  addons/ui/config.cpp
  addons/ui/fnc_progressBar.sqf
  addons/ui/script_component.hpp
  addons/ui/stringtable.xml
Labels: Feature

#866 Add optional mod to skip missing Mod check
  addons/versioning/XEH_postInitServer.sqf
  optionals/disable_missing_mod_check/$PBOPREFIX$
  optionals/disable_missing_mod_check/config.cpp
  optionals/disable_missing_mod_check/script_component.hpp
Labels: Enhancement
