Repository CBATeam/CBA_A3, pull requests merged in 2018-10, with the labels that each got.

#995 More JAM stuff
  addons/jam/CfgMagazineWells.hpp
  addons/jam/magwells_10mmAuto.hpp
  addons/jam/magwells_11x59R.hpp
  addons/jam/magwells_12gauge.hpp
  addons/jam/magwells_3006.hpp
  addons/jam/magwells_300BLK.hpp
  addons/jam/magwells_300WM.hpp
  addons/jam/magwells_303B.hpp
  addons/jam/magwells_32ACP.hpp
  addons/jam/magwells_338LM.hpp
  addons/jam/magwells_357Mag.hpp
  addons/jam/magwells_357SIG.hpp
  addons/jam/magwells_35mm.hpp
  addons/jam/magwells_380ACP.hpp
  addons/jam/magwells_38Spec.hpp
  addons/jam/magwells_38_200.hpp
  addons/jam/magwells_408CT.hpp
  addons/jam/magwells_40SW.hpp
  addons/jam/magwells_40mm.hpp
  addons/jam/magwells_455W.hpp
  addons/jam/magwells_45ACP.hpp
  addons/jam/magwells_45GAP.hpp
  addons/jam/magwells_50BMG.hpp
  addons/jam/magwells_545x39.hpp
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_580x42.hpp
  addons/jam/magwells_65C.hpp
  addons/jam/magwells_65G.hpp
  addons/jam/magwells_68SPC.hpp
  addons/jam/magwells_75x55.hpp
  addons/jam/magwells_762x25.hpp
  addons/jam/magwells_762x38R.hpp
  addons/jam/magwells_762x39.hpp
  addons/jam/magwells_762x51.hpp
  addons/jam/magwells_762x54.hpp
  addons/jam/magwells_763x25.hpp
  addons/jam/magwells_765x21.hpp
  addons/jam/magwells_792x33.hpp
  addons/jam/magwells_792x57.hpp
  addons/jam/magwells_8x22.hpp
  addons/jam/magwells_9x18.hpp
  addons/jam/magwells_9x19.hpp
  addons/jam/magwells_9x39.hpp
Labels: Enhancement

#998 Slot list manager Polish translation
  addons/ui/stringtable.xml
Labels: Translation

#1000 Remove BOM character from stringtables
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/ui/stringtable.xml
Labels: Cleanup

#997 JAM STANAG and 7.62.x51
  addons/jam/magwells_300BLK.hpp
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_65G.hpp
  addons/jam/magwells_68SPC.hpp
  addons/jam/magwells_762x39.hpp
  addons/jam/magwells_762x51.hpp
Labels: Enhancement

#1001 Add french translations for CBA UI
  addons/jam/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation

#1002 Add Turkish translations
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jam/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation

#1003 Settings - Automatically localize sub-category
  addons/settings/gui_createCategory.sqf
Labels: Enhancement

#1006 Complete Turkish Translations
  addons/accessory/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/settings/stringtable.xml
Labels: Translation

#1008 Fix duplicate stringtable for JAM
  addons/jam/stringtable.xml
Labels: Bug Fix

#1007 Add JAM magwell for Mk200
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_65x39.hpp
Labels: Enhancement

#1016 ignore locked statics in taskDefend
  addons/ai/fnc_taskDefend.sqf
  addons/ai/fnc_waypointGarrison.sqf
Labels: Bug Fix

#1018 up the pfh limit
  addons/common/fnc_addPerFrameHandler.sqf
Labels: Enhancement
