Repository CBATeam/CBA_A3, pull requests merged in 2018-02, with the labels that each got.

#885 Keybinding Diary - Localize displayName
  addons/help/XEH_postClientInit.sqf
Labels: Bug Fix

#887 fix and deprecate floatToString
  addons/main/script_macros_common.hpp
  addons/strings/fnc_floatToString.sqf
Labels: Cleanup

#888 undo #882
  addons/ui_helper/$PBOPREFIX$
  addons/ui_helper/config.cpp
  addons/ui_helper/script_component.hpp
  addons/ui_helper/script_dikCodes.hpp
Labels: Cleanup

#889 Add support for arbitrary character trimming 2
  addons/strings/fnc_leftTrim.sqf
  addons/strings/fnc_rightTrim.sqf
  addons/strings/fnc_trim.sqf
Labels: Feature

#890 add keyhandler to main map display
  addons/events/CfgEventHandlers.hpp
  addons/events/XEH_preStart.sqf
  addons/events/fnc_initDisplayMainMap.sqf
  addons/events/fnc_initDisplayMission.sqf
Labels: Bug Fix

#891 fix versioning code issues
  addons/versioning/XEH_postInitServer.sqf
Labels: Bug Fix
