Repository CBATeam/CBA_A3, pull requests merged in 2018-11, with the labels that each got.

#1019 Add Magwells for MMGs from Marksman DLC
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_338NM.hpp
  addons/jam/magwells_93x64.hpp
Labels: Enhancement

#1022 add header for PREP() macro
  addons/main/script_macros_common.hpp
Labels: Enhancement

#1005 CBA_fnc_currentUnit report UAV entity when controlling UAV
  addons/events/fnc_addPlayerEventHandler.sqf
Labels: Bug Fix, Enhancement

#1010 JAM - MkI EMR, 5.56 AK
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_762x51.hpp
Labels: Enhancement

#1020 Add more magazine wells
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_65x39.hpp
Labels: Enhancement

#1009 JAM - More magwells
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_300WM.hpp
  addons/jam/magwells_338LM.hpp
  addons/jam/magwells_40mm.hpp
  addons/jam/magwells_46x30.hpp
  addons/jam/magwells_762x51.hpp
  addons/jam/magwells_9x19.hpp
  addons/jam/magwells_9x21.hpp
Labels: Enhancement

#1012 Invisible Targets
  addons/ai/CfgVehicleIcons.hpp
  addons/ai/CfgVehicles.hpp
  addons/ai/IconInvisibleTarget.paa
  addons/ai/InvisibleTarget.p3d
  addons/ai/config.cpp
Labels: Feature

#1029 JAM - Added class for VZ58
  addons/jam/magwells_762x39.hpp
Labels: Enhancement

#1028 use custom OK button to fix ui bug
  addons/settings/fnc_initDisplayGameOptions.sqf
  addons/settings/fnc_openSettingsMenu.sqf
Labels: Bug Fix

#1025 fix findMax for arrays with duplicates
  addons/arrays/fnc_findMax.sqf
  addons/arrays/test_findMax.sqf
Labels: Bug Fix

#1031 Delete duplicates in console history
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
Labels: Enhancement

#1023 Update JR for 1.86
  addons/jr/cfgweapons.hpp
  addons/jr/jr_prep/CfgWeapons.hpp
Labels: Enhancement, v1.86

#1034 README.md: Bump release version on button
  README.md
Labels: Task
