Repository CBATeam/CBA_A3, pull requests merged in 2018-09, with the labels that each got.

#976 add Addon Options button to main menu
  addons/settings/RscDisplayMain.hpp
  addons/settings/XEH_preInit.sqf
  addons/settings/config.cpp
  addons/settings/fnc_initDisplayMain.sqf
  addons/settings/script_component.hpp
Labels: Enhancement

#975 add optional component to remove stock missions
  optionals/no_stock_missions/$PBOPREFIX$
  optionals/no_stock_missions/config.cpp
  optionals/no_stock_missions/no_stock_missions_prep/config.cpp
  optionals/no_stock_missions/no_stock_missions_prep/script_component.hpp
  optionals/no_stock_missions/script_component.hpp
Labels: Feature

#973 make server browser remember last used password for every server
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preClientInit.sqf
  addons/ui/XEH_preInit.sqf
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplayPassword.sqf
  addons/ui/stringtable.xml
Labels: Feature

#978 Let whitelisted UIDs save server settings
  addons/settings/fnc_set.sqf
Labels: Bug Fix

#974 add searchbar to mission browser
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Feature

#985 ProjectileTracking - Stop tracking stationary objects
  addons/diagnostic/fnc_projectileTracking_trackProjectile.sqf
Labels: Bug Fix

#984 CBA_fnc_getVolume not calculating volume correctly
  addons/common/fnc_getVolume.sqf
Labels: Bug Fix

#983 Polish translation updates
  addons/common/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation

#928 add Joint Ammo Magazines A3
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/config.cpp
  addons/jam/script_component.hpp
  addons/jam/stringtable.xml
Labels: Feature

#979 German translation, part 1
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jr/stringtable.xml
Labels: Translation

#980 German translation, part 2
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation

#981 German translation, part 3
  addons/modules/CfgVehicles.hpp
  addons/modules/stringtable.xml
Labels: Enhancement, Translation

#986 veteran29 Polish translation updates master
  addons/common/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
Labels: Dummy-Ticket, Translation

#988 German brands for JR and JAM components
  addons/jam/stringtable.xml
  addons/jr/stringtable.xml
Labels: Translation

#982 Add Feature Camera Player EH
  addons/common/CfgFunctions.hpp
  addons/common/XEH_preInit.sqf
  addons/common/fnc_getActiveFeatureCamera.sqf
  addons/common/fnc_registerFeatureCamera.sqf
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_removePlayerEventHandler.sqf
Labels: Enhancement, Feature

#987 Translate JAM module name into Polish
  addons/jam/stringtable.xml
  addons/jr/stringtable.xml
Labels: Translation

#990 Split/extend the magwell classes and files
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_10gauge.hpp
  addons/jam/magwells_12gauge.hpp
  addons/jam/magwells_145x114.hpp
  addons/jam/magwells_16gauge.hpp
  addons/jam/magwells_20gauge.hpp
  addons/jam/magwells_22LR.hpp
  addons/jam/magwells_3006.hpp
  addons/jam/magwells_303B.hpp
  addons/jam/magwells_32ACP.hpp
  addons/jam/magwells_357SIG.hpp
  addons/jam/magwells_380ACP.hpp
  addons/jam/magwells_40SW.hpp
  addons/jam/magwells_40mm.hpp
  addons/jam/magwells_45ACP.hpp
  addons/jam/magwells_545x39.hpp
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_580x42.hpp
  addons/jam/magwells_65x39.hpp
  addons/jam/magwells_762x25.hpp
  addons/jam/magwells_762x39.hpp
  addons/jam/magwells_762x51.hpp
  addons/jam/magwells_762x54.hpp
  addons/jam/magwells_77x58.hpp
  addons/jam/magwells_792x57.hpp
  addons/jam/magwells_8x22.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement
