Repository CBATeam/CBA_A3, pull requests merged in 2018-08, with the labels that each got.

#956 UI - Keep getFov params consistant with previous versions
  addons/ui/fnc_getFov.sqf
Labels: Bug Fix

#959 Workaround for settings size limitation
  addons/settings/fnc_parse.sqf
Labels: Bug Fix

#958 Fix Layout Editor running out of repositionable controls
  addons/ui/RscDisplayOptionsLayout.hpp
  addons/ui/config.cpp
Labels: Feature

#961 addon options button tooltip
  addons/settings/XEH_preInit.sqf
  addons/settings/stringtable.xml
Labels: Enhancement

#960 add tooltip about required mission start
  addons/common/stringtable.xml
  addons/keybinding/fnc_initDisplayConfigure.sqf
  addons/settings/fnc_initDisplayGameOptions.sqf
Labels: Enhancement

#963 Settings - More appropriate slider speeds
  addons/settings/fnc_gui_settingColor.sqf
  addons/settings/fnc_gui_settingSlider.sqf
Labels: Enhancement

#965 Add CBA_fnc_compatibleMagazines that supports mag wells
  addons/common/CfgFunctions.hpp
  addons/common/fnc_compatibleMagazines.sqf
Labels: Enhancement

#967 Settings - Add time setting type
  addons/settings/XEH_PREP.sqf
  addons/settings/XEH_preInit.sqf
  addons/settings/fnc_check.sqf
  addons/settings/fnc_gui_settingTime.sqf
  addons/settings/fnc_init.sqf
  addons/settings/gui.hpp
  addons/settings/gui_createCategory.sqf
  addons/settings/script_component.hpp
Labels: Feature

#970 French translation 3.8.0, fixed
  addons/accessory/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Enhancement

#971 tweak keybinding ui
  addons/keybinding/fnc_gui_update.sqf
  addons/keybinding/gui.hpp
  addons/settings/gui.hpp
Labels: Enhancement
