Repository CBATeam/CBA_A3, pull requests merged in 2018-07, with the labels that each got.

#947 XEH - Add compatiblity for Encore Destroyer (1.84)
  addons/xeh/CfgVehicles.hpp
Labels: Task

#948 Polish translation
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation

#949 don't loop forever with null group
  addons/common/fnc_deleteEntity.sqf
Labels: Bug Fix

#951 handle input gracefully in keybinding editKey ui function
  addons/keybinding/fnc_gui_editKey.sqf
Labels: Enhancement

#952 change color of name of temporarily changed settings
  addons/settings/fnc_gui_refresh.sqf
  addons/settings/fnc_gui_settingDefault.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
  addons/settings/gui_createCategory.sqf
  addons/settings/script_component.hpp
Labels: Enhancement

#950 don't skip next PFH if current one is removed while iterating through
  addons/common/fnc_removePerFrameHandler.sqf
  addons/common/init_perFrameHandler.sqf
Labels: Bug Fix

#894 indicate settings that need a mission restart
  addons/settings/applies_ca.paa
  addons/settings/fnc_gui_saveTempData.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
  addons/settings/fnc_init.sqf
  addons/settings/fnc_initDisplayGameOptions.sqf
  addons/settings/gui.hpp
  addons/settings/initSettings.sqf
  addons/settings/locked_ca.paa
  addons/settings/need_restart_ca.paa
  addons/settings/overwritten_ca.paa
  addons/settings/script_component.hpp
  addons/settings/stringtable.xml
Labels: Enhancement

#953 XEH - Compatiblity for Encore (1.84)
  addons/xeh/CfgVehicles.hpp
Labels: Cleanup
