Repository CBATeam/CBA_A3, pull requests merged in 2018-12, with the labels that each got.

#1038 Notifications - Polish translation
  addons/ui/stringtable.xml
Labels: Translation

#1040 Jam - Add pboprefix
  addons/jam/$PBOPREFIX$
Labels: Enhancement

#1042 ignore inherited arrays in magwells
  addons/common/fnc_compatibleMagazines.sqf
Labels: Bug Fix

#1039 getConfigEntry tweaks
  addons/common/fnc_getConfigEntry.sqf
Labels: Enhancement
