Repository CBATeam/CBA_A3, pull requests merged in 2019-02, with the labels that each got.

#1048 fix admin macros for usage in strings and config
  addons/main/script_macros_common.hpp
Labels: Bug Fix

#1055 Fix incorrect preprocessFileLineNumbers spelling
  addons/main/script_macros_common.hpp
Labels: Enhancement

#1053 Cache incompatibleClasses at preStart
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
Labels: Enhancement

#1057 Add return value to cba_fnc_preStart
  addons/xeh/fnc_preStart.sqf
Labels: Bug Fix

#1056 Resolve XEH redirect handlers
  addons/xeh/fnc_compileEventHandlers.sqf
Labels: Enhancement

#1047 fix for a CBA_missionTime initialization race condition
  addons/common/init_perFrameHandler.sqf
Labels: Bug Fix

#1036 port, reimplementation of ACE hints
  addons/ui/CfgFunctions.hpp
  addons/ui/CfgUIGrids.hpp
  addons/ui/fnc_notify.sqf
  addons/ui/script_component.hpp
  addons/ui/stringtable.xml
Labels: Feature

#1049 add CBA_fnc_selectRandomArray
  addons/arrays/CfgFunctions.hpp
  addons/arrays/fnc_selectRandomArray.sqf
Labels: Feature

#1058 remove 100Rnd mags magwell from non MX-SW MX variants
  addons/jam/CfgWeapons.hpp
Labels: Bug Fix

#1051 Overhaul activateAddons
  addons/common/CfgEventHandlers.hpp
  addons/common/XEH_preInit.sqf
  addons/common/XEH_preStart.sqf
Labels: Cleanup

#1062 add cba_jam to requiredAddons in cba_main
  addons/main/config.cpp
Labels: Bug Fix, Cleanup

#1061 Add P90, UMP40/45/9 & Beretta M9 magwells
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_40SW.hpp
  addons/jam/magwells_45ACP.hpp
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_570x28.hpp
  addons/jam/magwells_792x57.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1060 Remove unused local variable from CBA_fnc_isTurnedOut
  addons/common/fnc_isTurnedOut.sqf
Labels: Cleanup

#1059 add keepAspectRatio parameter to Layout Editor
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplayOptionsLayout.sqf
Labels: Feature

#1064 CfgFunctions for FlexiMenu ui subcomponent
  addons/ui/CfgFunctions.hpp
  addons/ui/flexiMenu/init.sqf
  addons/ui/script_component.hpp
Labels: Enhancement

#1066 add custom mission filter
  addons/ui/fnc_initDisplayRemoteMissions.sqf
  addons/ui/stringtable.xml
  optionals/no_stock_missions/$PBOPREFIX$
  optionals/no_stock_missions/config.cpp
  optionals/no_stock_missions/no_stock_missions_prep/config.cpp
  optionals/no_stock_missions/no_stock_missions_prep/script_component.hpp
  optionals/no_stock_missions/script_component.hpp
Labels: Feature

#1065 Add macros to skip adding headers to cfgFunctions
  addons/main/script_macros_common.hpp
  addons/main/script_mod.hpp
  addons/vectors/fnc_polar2vect.sqf
  addons/vectors/fnc_scaleVect.sqf
  addons/vectors/fnc_scaleVectTo.sqf
  addons/vectors/fnc_vect2polar.sqf
  addons/vectors/fnc_vectCross2D.sqf
  addons/vectors/fnc_vectDir.sqf
  addons/vectors/fnc_vectElev.sqf
  addons/vectors/fnc_vectMagn.sqf
  addons/vectors/fnc_vectMagn2D.sqf
  addons/vectors/fnc_vectSubtract.sqf
Labels: Enhancement

#1068 Convert rest of cfgFuncs to PATHTO_FNC macro
  addons/diagnostic/CfgFunctions.hpp
  addons/events/CfgFunctions.hpp
  addons/main/script_mod.hpp
  addons/modules/CfgFunctions.hpp
  addons/music/CfgFunctions.hpp
Labels: Cleanup

#1067 CREATE GAME menu tweaks
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Enhancement

#1052 Compile and cache configFile eventhandlers at preStart
  addons/xeh/CfgFunctions.hpp
  addons/xeh/fnc_compileEventHandlers.sqf
  addons/xeh/fnc_initDisplay.sqf
  addons/xeh/fnc_postInit.sqf
  addons/xeh/fnc_postInit_unscheduled.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
  addons/xeh/script_component.hpp
Labels: Cleanup, Enhancement

#1074 fix admin macros
  addons/main/script_macros_common.hpp
Labels: Bug Fix

#1075 add event for confirming changes in Layout Editor
  addons/ui/fnc_initDisplayOptionsLayout.sqf
Labels: Enhancement

#1072 Add Magazine Well support for MAAWS
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
Labels: Enhancement

#1071 Add Magazine Well support for SMAW
  addons/jam/CfgMagazineWells.hpp
Labels: Enhancement

#1073 Refactor Help Component
  addons/events/config.cpp
  addons/help/CfgEventhandlers.hpp
  addons/help/XEH_postClientInit.sqf
  addons/help/XEH_postInit.sqf
  addons/help/XEH_preClientInit.sqf
  addons/help/XEH_preInit.sqf
  addons/help/XEH_preStart.sqf
  addons/help/config.cpp
  addons/help/fnc_setCreditsLine.sqf
  addons/help/fnc_setVersionLine.sqf
  addons/help/gui.hpp
  addons/help/script_component.hpp
  addons/help/stringtable.xml
  addons/main_a3/CfgMods.hpp
  addons/main_a3/CfgSettings.hpp
  addons/main_a3/config.cpp
  addons/strings/CfgFunctions.hpp
  addons/strings/fnc_sanitizeHTML.sqf
Labels: Cleanup

#1076 More magwells
  addons/jam/CfgMagazineWells.hpp
  addons/jam/CfgWeapons.hpp
  addons/jam/magwells_22LR.hpp
  addons/jam/magwells_40SW.hpp
  addons/jam/magwells_45ACP.hpp
  addons/jam/magwells_570x28.hpp
  addons/jam/magwells_57x28.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1078 Fix missing base class in JAM and fix versioning caching
  addons/jam/CfgWeapons.hpp
  addons/versioning/CfgEventHandlers.hpp
  addons/versioning/XEH_postInitClient.sqf
Labels: Bug Fix, Cleanup

#1083 Re-add CBA_ui_fnc_menu
  addons/ui/CfgFunctions.hpp
Labels: Bug Fix

#1081 Activate all addons
  addons/common/XEH_preInit.sqf
  addons/common/XEH_preStart.sqf
Labels: Bug Fix
