Repository CBATeam/CBA_A3, pull requests merged in 2019-10, with the labels that each got.

#1233 Add magwells for the UZI and AS50
  addons/jam/magwells_50BMG.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1239 Add Missing Turkish Translations
  addons/ai/stringtable.xml
  addons/common/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/optics/stringtable.xml
  addons/ui/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Translation

#1240 XEH - Fix version report in rpt
  addons/xeh/fnc_preInit.sqf
Labels: Bug Fix

#1237 Add turret event
  addons/events/CfgFunctions.hpp
  addons/events/XEH_preInit.sqf
  addons/events/fnc_turretEvent.sqf
  addons/events/script_component.hpp
Labels: Feature

#1242 Replace all use of count as a forEach
  addons/common/init_perFrameHandler.sqf
  addons/jr/fnc_compatibleItems.sqf
  addons/statemachine/fnc_clockwork.sqf
  addons/statemachine/fnc_createFromConfig.sqf
  addons/xeh/fnc_addClassEventHandler.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_startFallbackLoop.sqf
Labels: Enhancement

#1245 Add support for 21:9 resolutions to CBA optics addon.
  addons/optics/cba_optic_big_pip.p3d
  addons/optics/cba_optic_small_pip.p3d
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_restartCamera.sqf
Labels: Bug Fix

#1247 localized diary topics replacement pull request
  addons/help/XEH_postInit.sqf
Labels: Enhancement

#1228 add XEH support to WeaponHolder(Simulated)
  addons/xeh/CfgVehicles.hpp
Labels: Enhancement

#1249 Update Japanese translation
  addons/ai/stringtable.xml
  addons/optics/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation
