Repository CBATeam/CBA_A3, pull requests merged in 2019-06, with the labels that each got.

#1152 Remove high capacity magwells from mk20
  addons/jam/CfgWeapons.hpp
Labels: Bug Fix

#1150 Replace %20 with space when displaying mission name
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplayDiary.sqf
  addons/ui/fnc_initDisplayMultiplayerSetup.sqf
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Enhancement

#1155 Extend 3den selectable date range from 1900 to 2050
  addons/common/Cfg3DEN.hpp
  addons/common/CfgVehicles.hpp
  addons/common/script_component.hpp
Labels: Enhancement

#1154 fix updating flashlight fx after attachment switch
  addons/accessory/fnc_switchAttachment.sqf
Labels: Bug Fix

#1160 fix scripted optics in pause menu in MP
  addons/optics/CfgEventHandlers.hpp
  addons/optics/fnc_initDisplayInterrupt.sqf
Labels: Bug Fix

#1161 check masses of items of disposable framework
  addons/disposable/XEH_preInit.sqf
Labels: Enhancement

#1163 update scripted optics effect radblur classes
  addons/optics/CfgOpticsEffect.hpp
Labels: Enhancement

#1162 rotate scripted optic according to weapon bank
  addons/optics/XEH_PREP.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_gunBank.sqf
Labels: Enhancement

#1158 add cartridge ejection effect on repeat
  addons/events/fnc_weaponEvents.sqf
Labels: Feature

#1164 optimize CBA_fnc_randomVector3D
  addons/vectors/fnc_randomVector3D.sqf
Labels: Enhancement

#1165 handle expressions in CfgOpticsEffect
  addons/optics/CfgOpticsEffect.hpp
  addons/optics/fnc_updateOpticInfo.sqf
Labels: Bug Fix

#1166 replace more %xy in mission names
  addons/strings/CfgFunctions.hpp
  addons/strings/fnc_decodeURL.sqf
  addons/strings/script_component.hpp
  addons/ui/fnc_initDisplayDiary.sqf
  addons/ui/fnc_initDisplayInterrupt.sqf
  addons/ui/fnc_initDisplayMultiplayerSetup.sqf
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Enhancement

#1157 update CBA_fnc_uniqueUnitItems
  addons/common/fnc_uniqueUnitItems.sqf
Labels: Enhancement

#1168 Fix CBA_fnc_removeItemCargo removing all containers instead of specified quantity
  addons/common/fnc_removeItemCargo.sqf
  addons/common/test_inventory.sqf
Labels: Bug Fix

#1173 Use BI's new matrix commands
  addons/vectors/fnc_matrixProduct3D.sqf
  addons/vectors/fnc_matrixTranspose.sqf
  addons/vectors/fnc_vectMap3D.sqf
Labels: Cleanup
