Repository CBATeam/CBA_A3, pull requests merged in 2019-09, with the labels that each got.

#1217 Add period at the end of target debug info log
  addons/diagnostic/XEH_preInit.sqf
Labels: Bug Fix, Ignore Changelog

#1219 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Ignore Changelog, Tools

#1222 Cleanup CfgPatches and use VERSION_CONFIG consistently
  addons/accessory/MRT_AccFncs/config.cpp
  addons/accessory/config.cpp
  addons/ai/config.cpp
  addons/arrays/config.cpp
  addons/common/config.cpp
  addons/diagnostic/config.cpp
  addons/disposable/config.cpp
  addons/events/config.cpp
  addons/hashes/config.cpp
  addons/help/config.cpp
  addons/jam/config.cpp
  addons/jam/jam_finish/config.cpp
  addons/jr/config.cpp
  addons/jr/jr_prep/config.cpp
  addons/keybinding/config.cpp
  addons/main/config.cpp
  addons/main_a3/config.cpp
  addons/modules/config.cpp
  addons/music/config.cpp
  addons/network/config.cpp
  addons/optics/config.cpp
  addons/settings/config.cpp
  addons/statemachine/config.cpp
  addons/strings/config.cpp
  addons/ui/config.cpp
  addons/vectors/config.cpp
  addons/versioning/config.cpp
  addons/xeh/config.cpp
Labels: Cleanup, Enhancement

#1221 Improve VERSION_CONFIG
  addons/help/XEH_preStart.sqf
  addons/main/script_macros_common.hpp
  addons/main/script_mod.hpp
Labels: Enhancement

#1201 Add Facewear Randomization
  addons/common/CfgFunctions.hpp
  addons/common/XEH_preInit.sqf
  addons/common/fnc_randomizeFacewear.sqf
Labels: Feature

#1224 fix crash when hosting server with large ui scale
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Bug Fix

#1223 report backpacks with CBA_fnc_getItemConfig
  addons/common/fnc_getItemConfig.sqf
Labels: Bug Fix

#1209 Common - Prevent endless loop with waitAndExec
  addons/common/init_perFrameHandler.sqf
Labels: Bug Fix

#1192 Put tags in CfgMusic.hpp into quotes
  addons/music/CfgMusic.hpp
Labels: Cleanup

#1212 add CONTACT SERVER ADMIN header to signature mismatch message
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplayMessageBox.sqf
  addons/ui/stringtable.xml
Labels: Enhancement, Help Wanted, Ignore Changelog

#1227 JR - Add muzzle slots for 4.6mm and 7.62x54R
  addons/jr/jr_classes.hpp
Labels: Enhancement

#1231 Slider UI style improvements for cba_settings
  addons/settings/gui.hpp
Labels: Enhancement

#1225 Remove excessive concatenation operators from macros library
  addons/main/script_macros_common.hpp
Labels: Cleanup

#1229 fix includeDisabled flag in CBA_fnc_supportMonitor
  addons/xeh/fnc_supportMonitor.sqf
Labels: Bug Fix
