Repository CBATeam/CBA_A3, pull requests merged in 2019-07, with the labels that each got.

#1175 Notify - Skippable parameter, Lifetime Setting, Use in Accessory component
  addons/accessory/fnc_switchAttachment.sqf
  addons/ui/XEH_preInit.sqf
  addons/ui/fnc_notify.sqf
  addons/ui/initSettings.sqf
  addons/ui/script_component.hpp
  addons/ui/stringtable.xml
Labels: Enhancement

#1176 Scripted optics updates
  addons/optics/XEH_preInit.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_updateOpticInfo.sqf
Labels: Bug Fix, Enhancement

#1177 add failure code argument to fnc_progressBar
  addons/ui/fnc_progressBar.sqf
Labels: Enhancement

#1182 XEH - Add direct XEH support for 1.94 objects
  addons/xeh/CfgVehicles.hpp
Labels: 1.94, Task

#1171 Update loadorder for 1.94 Contact DLC
  addons/common/config.cpp
  addons/main/script_mod.hpp
Labels: 1.94, Task

#1179 Add magwells for SCAR rifle magazines when EGLM is mounted
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_762x51.hpp
Labels: Enhancement

#1183 1.94 - Fix GL magwells
  addons/jam/CfgWeapons.hpp
  addons/jam/jam_finish/CfgWeapons.hpp
  addons/jam/jam_finish/config.cpp
  addons/jam/jam_finish/script_component.hpp
Labels: 1.94, Task

#1181 Add Contact DLC JointRails
  addons/jam/config.cpp
  addons/jr/Cfgweapons.hpp
  addons/jr/jr_classes.hpp
Labels: 1.94, Task

#1188 implement addWeaponWithAttachmentsCargoGlobal command
  addons/common/fnc_removeBackpackCargo.sqf
  addons/common/fnc_removeItemCargo.sqf
  addons/common/fnc_removeWeaponCargo.sqf
  addons/common/test_inventory.sqf
  addons/disposable/fnc_firedDisposable.sqf
Labels: 1.94, Enhancement

#1186 fix minor ui issues with Contact DLC ui modifications
  addons/settings/fnc_gui_sourceChanged.sqf
  addons/ui/fnc_initDisplayInterrupt.sqf
Labels: 1.94, Bug Fix

#1184 joint rails - enoch attachment classes compatibility - Variant A
  addons/jr/CfgWeapons.hpp
  addons/jr/jr_prep/CfgWeapons.hpp
Labels: 1.94, Task

#1189 add legacy JR component
  addons/jr/config.cpp
  addons/legacy_jr/$PBOPREFIX$
  addons/legacy_jr/CfgWeapons.hpp
  addons/legacy_jr/config.cpp
  addons/legacy_jr/legacy_jr_prep/CfgWeapons.hpp
  addons/legacy_jr/legacy_jr_prep/config.cpp
  addons/legacy_jr/legacy_jr_prep/script_component.hpp
  addons/legacy_jr/script_component.hpp
  addons/legacy_jr/stringtable.xml
Labels: 1.94, Task
