Repository CBATeam/CBA_A3, pull requests merged in 2019-12, with the labels that each got.

#1262 update CBA_fnc_dropWeapon
  addons/common/fnc_dropWeapon.sqf
  addons/common/fnc_removeWeapon.sqf
Labels: Bug Fix, Enhancement

#1268 remove line number and filename from LOG, ERROR, WARNING
  addons/main/script_macros_common.hpp
Labels: Cleanup

#1267 Standardize XEH and Versioning logging prefixs
  addons/disposable/script_component.hpp
  addons/optics/script_component.hpp
  addons/versioning/XEH_postInit.sqf
  addons/versioning/XEH_postInitClient.sqf
  addons/versioning/script_component.hpp
  addons/xeh/fnc_addClassEventHandler.sqf
  addons/xeh/fnc_compileEventHandlers.sqf
  addons/xeh/fnc_init.sqf
  addons/xeh/fnc_initDisplay3DEN.sqf
  addons/xeh/fnc_postInit.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
  addons/xeh/script_component.hpp
Labels: Cleanup

#1263 FSM Editor Config for CBA Statemachine
  addons/statemachine/CBA_FSMEditor.cfg
Labels: Enhancement

#1265 Added French translation and/or correction
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/common/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/jam/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/optics/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation
