Repository CBATeam/CBA_A3, pull requests merged in 2019-03, with the labels that each got.

#1087 fix undefined flexi menu functions
  addons/ui/CfgFunctions.hpp
  addons/ui/RscDisplayOptionsLayout.hpp
  addons/ui/XEH_preInit.sqf
Labels: Bug Fix

#1086 fix stock mission filter on dedicated server
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Bug Fix

#1088 Update Japanese translation
  addons/common/stringtable.xml
  addons/jam/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation

#1084 Preload 3DEN and Zeus item lists
  addons/ui/CfgEventHandlers.hpp
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_initDisplay3DEN.sqf
  addons/ui/fnc_initDisplayCurator.sqf
  addons/ui/fnc_preload3DEN.sqf
  addons/ui/fnc_preloadCurator.sqf
  addons/ui/script_component.hpp
  addons/ui/test_preload.sqf
Labels: Feature

#1090 Update DIK Codes include path
  addons/events/script_component.hpp
  addons/keybinding/fnc_addKeybind.sqf
  addons/ui/flexiMenu/fnc_add.sqf
Labels: Enhancement

#1089 Add HC note to initDisplayRemoteMissions
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Ignore Changelog

#1079 add scriptNames to functions for debugging
  addons/common/init_perFrameHandler.sqf
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_startFallbackLoop.sqf
Labels: Feature, Functions

#1080 addPlayerEh - Skip checking turretPath in not in vehicle
  addons/events/fnc_addPlayerEventHandler.sqf
Labels: Enhancement

#1092 settings, fix set for out of bounds priority
  addons/settings/script_component.hpp
Labels: Bug Fix

#1093 Fix CBA_fnc_getMuzzles example
  addons/common/fnc_getMuzzles.sqf
Labels: Functions

#1095 fix spacing for mods without description
  addons/help/XEH_preStart.sqf
Labels: Bug Fix

#1094 fix error popup in Arsenal Garage
  addons/ai/CfgVehicles.hpp
  addons/main_a3/CfgMods.hpp
  tools/make.py
Labels: Bug Fix

#1099 keep Editor in local hosted mission browser while hiding stock missions
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Bug Fix
