Repository CBATeam/CBA_A3, pull requests merged in 2019-05, with the labels that each got.

#1133 JAM - Add 1.92 vanilla mag wells
  addons/jam/CfgWeapons.hpp
Labels: Task

#1130 Change getVolume to use visual clipping type
  addons/common/fnc_getVolume.sqf
Labels: Enhancement

#1131 JR - Fix suppressor file path changes in 1.92
  addons/jr/cfgweapons.hpp
Labels: Bug Fix

#1125 add setting to disable disposable launchers
  addons/disposable/XEH_preInit.sqf
  addons/disposable/fnc_firedDisposable.sqf
  addons/disposable/fnc_initDisplayInventory.sqf
  addons/disposable/fnc_replaceMagazineCargo.sqf
  addons/disposable/initSettings.sqf
  addons/disposable/stringtable.xml
  addons/events/initSettings.sqf
Labels: Enhancement

#1135 Use += for magwells
  addons/jam/CfgWeapons.hpp
Labels: Enhancement

#1134 fix fail to read settings from settings file
  addons/disposable/initSettings.sqf
  addons/optics/initSettings.sqf
  addons/settings/XEH_preInit.sqf
  addons/settings/fnc_addSetting.sqf
  addons/settings/initSettings.sqf
Labels: Bug Fix

#1140 fix Curator and 3DEN cargo attributes
  addons/ui/fnc_preload3DEN.sqf
  addons/ui/fnc_preloadCurator.sqf
  addons/ui/test_preload.sqf
Labels: Bug Fix

#1143 adds optics hidePeripheralVision config entry
  addons/optics/RscInGameUI.hpp
  addons/optics/XEH_preInit.sqf
  addons/optics/fnc_loadScriptedOptic.sqf
  addons/optics/fnc_updateOpticInfo.sqf
  addons/optics/script_component.hpp
Labels: Enhancement

#1142 add optics reticleSafezoneSize config entry
  addons/optics/RscInGameUI.hpp
  addons/optics/XEH_preInit.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_animateScriptedOpticRecoil.sqf
  addons/optics/fnc_loadScriptedOptic.sqf
  addons/optics/fnc_updateOpticInfo.sqf
  addons/optics/script_component.hpp
Labels: Enhancement

#1141 add manual reticle night switch keybind
  addons/accessory/XEH_preInitClient.sqf
  addons/optics/RscInGameUI.hpp
  addons/optics/XEH_preInit.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_animateScriptedOpticRecoil.sqf
  addons/optics/fnc_loadScriptedOptic.sqf
  addons/optics/fnc_updateOpticInfo.sqf
  addons/optics/initKeybinds.sqf
  addons/optics/script_component.hpp
  addons/optics/stringtable.xml
Labels: Enhancement

#1138 add buildingPos dummy object
  addons/ai/BuildingPos.p3d
  addons/ai/CfgAddons.hpp
  addons/ai/CfgFunctions.hpp
  addons/ai/CfgVehicles.hpp
  addons/ai/config.cpp
  addons/ai/fnc_buildingPositions.sqf
  addons/ai/stringtable.xml
Labels: Feature

#1144 optimize magwell preloading
  addons/ui/fnc_preload3DEN.sqf
  addons/ui/fnc_preloadCurator.sqf
  addons/ui/test_preload.sqf
Labels: Enhancement

#1151 add CBA_fnc_randomVector3D
  addons/vectors/CfgFunctions.hpp
  addons/vectors/fnc_randomVector3D.sqf
Labels: Feature

#1148 Change descriptionShort of legacy Zafir mags
  addons/jam/CfgMagazines.hpp
  addons/jam/config.cpp
  addons/jam/stringtable.xml
Labels: Bug Fix
