Repository CBATeam/CBA_A3, pull requests merged in 2019-08, with the labels that each got.

#1197 fix optic tilting in vehicles
  addons/optics/fnc_gunBank.sqf
Labels: Bug Fix

#1191 fix scripted optics pip effect
  addons/optics/fnc_restartCamera.sqf
Labels: Bug Fix

#1199 Nobin xeh
  addons/ee/$NOBIN$
  addons/ee/$PBOPREFIX$
  addons/ee/config.cpp
  addons/ee/script_component.hpp
  addons/xeh/CfgVehicles.hpp
  addons/xeh/ee/config.cpp
Labels: Task

#1200 fix ee
  addons/ee/config.cpp
Labels: Ignore Changelog

#1202 6.5mm magwells fix
  addons/jam/magwells_65x39.hpp
Labels: Bug Fix

#1203 Czech translation
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jam/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/optics/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Translation

#1213 Default transition targetstate to transition configName
  addons/statemachine/fnc_createFromConfig.sqf
Labels: Enhancement

#1214 handle returned assignments in key events
  addons/events/fnc_keyHandlerDown.sqf
Labels: Bug Fix

#1216 Add Spanish translation for UI category
  addons/ui/stringtable.xml
Labels: Translation
