Repository CBATeam/CBA_A3, pull requests merged in 2019-04, with the labels that each got.

#1108 Use Python 3.6 on Travis CI
  .travis.yml
Labels: Tools

#1111 add CBA_fnc_addSetting
  addons/settings/CfgFunctions.hpp
  addons/settings/config.cpp
  addons/settings/fnc_addSetting.sqf
  addons/settings/fnc_init.sqf
Labels: Enhancement

#1107 Add trigger options to weapon events
  addons/events/XEH_postInit.sqf
  addons/events/XEH_preInit.sqf
  addons/events/fnc_weaponEvents.sqf
  addons/events/initSettings.sqf
  addons/events/stringtable.xml
Labels: Feature

#1110 Minor Macro related fixes
  addons/common/fnc_addPlayerAction.sqf
  addons/common/fnc_removePlayerAction.sqf
  addons/events/fnc_registerChatCommand.sqf
  addons/ui/flexiMenu/fnc_remove.sqf
  addons/ui/flexiMenu/fnc_setObjectMenuSource.sqf
  addons/xeh/fnc_endLoadingScreen.sqf
  addons/xeh/fnc_initDisplay.sqf
  addons/xeh/fnc_startLoadingScreen.sqf
Labels: Bug Fix, Cleanup

#1104 More WW2 era magwells
  addons/jam/CfgMagazineWells.hpp
  addons/jam/magwells_25ACP.hpp
  addons/jam/magwells_30Carbine.hpp
  addons/jam/magwells_32ACP.hpp
  addons/jam/magwells_380ACP.hpp
  addons/jam/magwells_75x54mmFrench.hpp
  addons/jam/magwells_762x54.hpp
  addons/jam/magwells_763x25.hpp
  addons/jam/magwells_765x20Longue.hpp
  addons/jam/magwells_792x107mmDS.hpp
  addons/jam/magwells_792x57.hpp
  addons/jam/magwells_8x50mmR_Mannlicher.hpp
  addons/jam/magwells_8x56mmR.hpp
  addons/jam/magwells_9x18.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1112 Polish translation updates
  addons/events/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation

#1113 2D Optics polish translation
  addons/2doptics/stringtable.xml
Labels: Translation

#1105 Scripted 2D optics component
  addons/2doptics/$PBOPREFIX$
  addons/2doptics/CfgCarryHandleTypes.hpp
  addons/2doptics/CfgEventHandlers.hpp
  addons/2doptics/CfgOpticsEffect.hpp
  addons/2doptics/CfgPIPItems.hpp
  addons/2doptics/RscInGameUI.hpp
  addons/2doptics/XEH_PREP.sqf
  addons/2doptics/XEH_preInit.sqf
  addons/2doptics/XEH_preStart.sqf
  addons/2doptics/cba_optic_big_100.p3d
  addons/2doptics/cba_optic_big_70.p3d
  addons/2doptics/cba_optic_big_80.p3d
  addons/2doptics/cba_optic_big_90.p3d
  addons/2doptics/cba_optic_big_pip.p3d
  addons/2doptics/cba_optic_small_100.p3d
  addons/2doptics/cba_optic_small_70.p3d
  addons/2doptics/cba_optic_small_80.p3d
  addons/2doptics/cba_optic_small_90.p3d
  addons/2doptics/cba_optic_small_pip.p3d
  addons/2doptics/config.cpp
  addons/2doptics/fnc_animateScriptedOptic.sqf
  addons/2doptics/fnc_animateScriptedOpticRecoil.sqf
  addons/2doptics/fnc_changeCarryHandleOpticClass.sqf
  addons/2doptics/fnc_changePIPOpticClass.sqf
  addons/2doptics/fnc_currentOptic.sqf
  addons/2doptics/fnc_initDisplayInterrupt.sqf
  addons/2doptics/fnc_loadScriptedOptic.sqf
  addons/2doptics/fnc_restartCamera.sqf
  addons/2doptics/fnc_setOpticMagnification.sqf
  addons/2doptics/fnc_setOpticMagnificationHelper.sqf
  addons/2doptics/fnc_setOpticMagnificationHelperZeroing.sqf
  addons/2doptics/fnc_updateOpticInfo.sqf
  addons/2doptics/initSettings.sqf
  addons/2doptics/reticles/pip.rvmat
  addons/2doptics/reticles/scopeblack.rvmat
  addons/2doptics/reticles/scopeblack_big_100_ca.paa
  addons/2doptics/reticles/scopeblack_big_70_ca.paa
  addons/2doptics/reticles/scopeblack_big_80_ca.paa
  addons/2doptics/reticles/scopeblack_big_90_ca.paa
  addons/2doptics/reticles/scopeblack_ca.paa
  addons/2doptics/reticles/scopeblack_small_100_ca.paa
  addons/2doptics/reticles/scopeblack_small_70_ca.paa
  addons/2doptics/reticles/scopeblack_small_80_ca.paa
  addons/2doptics/reticles/scopeblack_small_90_ca.paa
  addons/2doptics/script_component.hpp
  addons/2doptics/stringtable.xml
  addons/main/config.cpp
Labels: Feature

#1118 remove unused code
  addons/optics/fnc_initDisplayInterrupt.sqf
Labels: Bug

#1120 optimize fallback loop
  addons/xeh/fnc_startFallbackLoop.sqf
Labels: Enhancement

#1122 fix CBA_fnc_compatibleMagazines skipping muzzle magazines
  addons/common/fnc_compatibleMagazines.sqf
Labels: Bug Fix

#1124 Add Italian translation
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/optics/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation

#1121 Fix number input for notify
  addons/ui/fnc_notify.sqf
Labels: Bug Fix

#1127 followup Japanese translation for disposable
  addons/disposable/stringtable.xml
Labels: Translation

#1126 Update Japanese translation
  addons/common/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/optics/stringtable.xml
Labels: Translation

#1129 fix headDir 1.92
  addons/common/fnc_headDir.sqf
Labels: Bug Fix
