Repository CBATeam/CBA_A3, pull requests merged in 2019-11, with the labels that each got.

#1244 Add CBA_fnc_selectBest function
  addons/arrays/CfgFunctions.hpp
  addons/arrays/fnc_selectBest.sqf
Labels: Feature

#1250 fix Russian keybinding localization error
  addons/keybinding/XEH_preStart.sqf
  addons/keybinding/script_component.hpp
Labels: Bug Fix, Enhancement

#1252 add German translations
  addons/ui/stringtable.xml
Labels: Translation

#1251 Ai modules override disabled AI pathing
  addons/ai/fnc_taskAttack.sqf
  addons/ai/fnc_taskDefend.sqf
  addons/ai/fnc_taskPatrol.sqf
  addons/ai/fnc_taskSearchArea.sqf
Labels: Enhancement

#1254 Fix optics camera restart handling for Zeus
  addons/optics/fnc_restartCamera.sqf
  addons/optics/script_component.hpp
Labels: Bug Fix

#1253 Fix JIP event removal on dedicated client
  addons/events/XEH_preInit.sqf
  addons/events/fnc_removeGlobalEventJIP.sqf
Labels: Bug Fix

#1259 add\update Tchinese Translation
  addons/ai/stringtable.xml
  addons/common/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/jam/stringtable.xml
  addons/optics/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Translation

#1260 Update missing string on tchinese
  addons/optics/stringtable.xml
Labels: Translation
