Repository CBATeam/CBA_A3, pull requests merged in 2020-12, with the labels that each got.

#1394 Translations - Fix French Translations (Ai)
  addons/ai/stringtable.xml
Labels: Translation

#1379 Fixed CBA_fnc_addKeybind and custom controls
  addons/keybinding/fnc_addKeybind.sqf
Labels: Bug Fix

#1382 add Documentation for default parameter in hashGet
  addons/hashes/fnc_hashCreate.sqf
  addons/hashes/fnc_hashGet.sqf
Labels: Enhancement, Support

#1397 Magwells - Add CZ 807 Magwell
  addons/jam/magwells_762x39.hpp
Labels: Enhancement

#1393 AI - Put Invisible Target Soldier String Key Into CBA
  addons/ai/CfgVehicles.hpp
  addons/ai/stringtable.xml
Labels: Enhancement, Translation
