Repository CBATeam/CBA_A3, pull requests merged in 2020-10, with the labels that each got.

#1367 Add IMI Galil magwells
  addons/jam/magwells_556x45.hpp
  addons/jam/magwells_762x51.hpp
Labels: Enhancement

#1335 JR - Ensure class names returned by compatibleItems are in config case
  addons/jr/fnc_compatibleItems.sqf
Labels: Enhancement

#1330 Add CBA_fnc_canAddItem
  addons/common/CfgFunctions.hpp
  addons/common/fnc_canAddItem.sqf
Labels: Feature

#1346 Invisible Target improvements
  addons/ai/CfgVehicles.hpp
  addons/ai/InvisibleTarget.p3d
  addons/ai/InvisibleTargetVehicle.p3d
  addons/ai/config.cpp
  addons/ai/stringtable.xml
Labels: Bug Fix, Feature

#1350 add CBA_fnc_hashValues
  addons/hashes/CfgFunctions.hpp
  addons/hashes/fnc_hashValues.sqf
Labels: Feature
