Repository CBATeam/CBA_A3, pull requests merged in 2020-11, with the labels that each got.

#1384 Add Disassembled XEH support
  addons/xeh/script_component.hpp
  addons/xeh/script_xeh.hpp
Labels: Enhancement

#1381 Fix Hemtt File-Patching
  hemtt.toml
Labels: Ignore Changelog, Tools

#1377 hashValues - don't copy arrays
  addons/hashes/fnc_hashKeys.sqf
  addons/hashes/fnc_hashValues.sqf
  addons/hashes/test_hashes.sqf
Labels: Bug Fix

#1387 Translation - Add French Translations (Ai)
  addons/ai/stringtable.xml
Labels: Translation

#1390 Fix statemachine conditions using global variables
  addons/statemachine/script_component.hpp
Labels: Bug Fix
