Repository CBATeam/CBA_A3, pull requests merged in 2020-04, with the labels that each got.

#1319 Tools - Fix HEMTT version set and set version in README.md
  hemtt.toml
Labels: Bug Fix, Tools

#1322 Fix waypoint positioning for exact placement
  addons/ai/fnc_addWaypoint.sqf
  addons/ai/fnc_clearWaypoints.sqf
  addons/ai/fnc_searchNearby.sqf
Labels: Bug Fix

#1311 XEH - Update configs for 1.98 (Oldman)
  addons/common/config.cpp
  addons/main/script_mod.hpp
  addons/xeh/CfgVehicles.hpp
Labels: Task

#1317 Tools - Show version when installing HEMTT
  .github/workflows/arma.yml
  tools/setup.bat
Labels: Ignore Changelog, Tools

#1328 Inventory - Add context menu options for pointers and optics
  addons/accessory/XEH_preInit.sqf
Labels: Enhancement
