Repository CBATeam/CBA_A3, pull requests merged in 2020-02, with the labels that each got.

#1288 skip attachment switch inside vehicles
  addons/accessory/XEH_preInit.sqf
  addons/accessory/XEH_preInitClient.sqf
  addons/accessory/config.cpp
  addons/accessory/fnc_switchAttachment.sqf
  addons/accessory/script_component.hpp
Labels: Enhancement

#1291 Prevent double execution of Killed event on the same body
  addons/xeh/fnc_preInit.sqf
Labels: Enhancement

#1285 Change color of overwritten settings equal to overwrite to orange
  addons/settings/fnc_gui_settingCheckbox.sqf
  addons/settings/fnc_gui_settingColor.sqf
  addons/settings/fnc_gui_settingDefault.sqf
  addons/settings/fnc_gui_settingEditbox.sqf
  addons/settings/fnc_gui_settingList.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
  addons/settings/fnc_gui_settingSlider.sqf
  addons/settings/fnc_gui_settingTime.sqf
  addons/settings/script_component.hpp
  addons/settings/stringtable.xml
Labels: Enhancement

#1289 optimize player events
  addons/events/XEH_preInit.sqf
  addons/events/XEH_preStart.sqf
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
  addons/events/fnc_removePlayerEventHandler.sqf
Labels: Enhancement

#1290 Settings - Add support for percentage sliders
  addons/settings/XEH_preInit.sqf
  addons/settings/fnc_addSetting.sqf
  addons/settings/fnc_gui_settingSlider.sqf
  addons/settings/fnc_init.sqf
  addons/settings/gui.hpp
  addons/settings/gui_createCategory.sqf
Labels: Enhancement

#1286 Add magwells for KSVK, AA-12, CZ-750, vz 59
  addons/jam/CfgMagazineWells.hpp
  addons/jam/magwells_127x108.hpp
  addons/jam/magwells_12gauge.hpp
  addons/jam/magwells_762x51.hpp
  addons/jam/magwells_762x54.hpp
Labels: Enhancement

#1292 Update fnc_gui_settingOverwrite.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
Labels: Ignore Changelog

#1296 Settings - Fix list default value tooltip for non-numeric values
  addons/settings/gui_createCategory.sqf
Labels: Bug Fix

#1293 Tools - Removed deprecated Mikero tools arguments make.py
  tools/make.py
Labels: Ignore Changelog, Tools
