Repository CBATeam/CBA_A3, pull requests merged in 2020-01, with the labels that each got.

#1273 Prevent script error on comment lines in settings file
  addons/settings/fnc_parse.sqf
Labels: Bug Fix

#1272 Add JSON parse and encode function
  addons/hashes/CfgFunctions.hpp
  addons/hashes/fnc_encodeJSON.sqf
  addons/hashes/fnc_parseJSON.sqf
  addons/hashes/test.sqf
  addons/hashes/test_parseJSON.sqf
  addons/hashes/test_parseJSON_config.json
Labels: Feature

#1279 Add default value to tooltip of "Reset to default" button in settings
  addons/settings/gui.hpp
  addons/settings/gui_createCategory.sqf
Labels: Enhancement

#1275 Don't URLdecode when URL has no encoded characters
  addons/strings/fnc_decodeURL.sqf
Labels: Enhancement

#1271 CBA_fnc_sortNestedArray - Preserve order of elements with same sorting value
  addons/arrays/fnc_sortNestedArray.sqf
Labels: Bug Fix

#1277 optimize default value for radius in CBA_fnc_addWaypoint etc.
  addons/ai/fnc_addWaypoint.sqf
  addons/ai/fnc_clearWaypoints.sqf
  addons/ai/fnc_searchNearby.sqf
  addons/ai/fnc_taskAttack.sqf
  addons/ai/fnc_taskPatrol.sqf
  addons/ai/fnc_taskSearchArea.sqf
  addons/ai/fnc_waypointGarrison.sqf
Labels: Enhancement

#1278 Update make.py for changes to pboProject
  tools/make.py
Labels: Ignore Changelog

#1274 AI: Don't halt planned movement for empty group
  addons/ai/fnc_clearWaypoints.sqf
Labels: Bug Fix

#1280 Settings - Localize list default value tooltip
  addons/settings/gui_createCategory.sqf
Labels: Ignore Changelog

#1281 restore selected tab in settings ui
  addons/settings/fnc_gui_configure.sqf
  addons/settings/fnc_initDisplayGameOptions.sqf
  addons/settings/fnc_openSettingsMenu.sqf
Labels: Enhancement
