Repository CBATeam/CBA_A3, pull requests merged in 2020-03, with the labels that each got.

#1304 fix missing default value for cba_optics_OpticBodyTextureSize
  addons/optics/XEH_preInit.sqf
Labels: Bug Fix

#1305 add Support for Waypoints to cba_fnc_getPos
  addons/common/fnc_getPos.sqf
Labels: Enhancement

#1306 createPerFrameHandlerObject - remove pfeh if location deleted
  addons/common/fnc_createPerFrameHandlerObject.sqf
Labels: Bug Fix

#1307 Update make.py
  tools/make.py
Labels: Ignore Changelog

#1301 Events - fix loadout player event args
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
Labels: Bug Fix

#1299 Return target exec result back to executor
  addons/diagnostic/XEH_preInit.sqf
  addons/diagnostic/fnc_initTargetDebugConsole.sqf
Labels: Enhancement

#1294 add CBA_fnc_switchableAttachments
  addons/accessory/CfgEventHandlers.hpp
  addons/accessory/CfgFunctions.hpp
  addons/accessory/config.cpp
  addons/accessory/fnc_switchableAttachments.sqf
Labels: Enhancement

#1308 Added 762x39 SKS magazine wells
  addons/jam/magwells_762x39.hpp
Labels: Enhancement

#1309 Fix CBA_fnc_formatNumber for small negative numbers
  addons/strings/fnc_formatNumber.sqf
Labels: Bug Fix

#1145 Adapt to HEMTT
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .gitignore
  .travis.yml
  addons/ui/flexiMenu/data/menu_arma2.hpp
  addons/ui/flexiMenu/data/menu_buttonList.hpp
  addons/ui/flexiMenu/data/menu_iconRow.hpp
  addons/ui/flexiMenu/data/menu_popup.hpp
  build.bat
  build_release.bat
  circle.yml
  hemtt.toml
  include/a3/ui_f/$PBOPREFIX$
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  tools/check_strings.py
  tools/setup.bat
Labels: Tools

#1303 Add Item Context Menu Framework
  addons/ui/CfgEventHandlers.hpp
  addons/ui/CfgFunctions.hpp
  addons/ui/RscTitles.hpp
  addons/ui/XEH_preInit.sqf
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_addItemContextMenuOption.sqf
  addons/ui/fnc_consumeItem.sqf
  addons/ui/fnc_initDisplayInventory.sqf
  addons/ui/fnc_openItemContextMenu.sqf
Labels: Feature

#1310 Tools - Set build number in HEMTT release build
  addons/main/script_version.hpp
  hemtt.toml
Labels: Tools

#1312 Events - Fix "turretweapon" player event when retro
  addons/events/fnc_addPlayerEventHandler.sqf
Labels: Bug Fix

#1314 Fix CBA_fnc_consumeItem direct call
  addons/ui/fnc_consumeItem.sqf
Labels: Bug Fix

#1313 Events - Player events will report driver seat as turret [-1]
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
Labels: Bug Fix
