Repository CBATeam/CBA_A3, pull requests merged in 2021-05, with the labels that each got.

#1443 Strings - Fix for formatElapsedTime rounding error
  addons/strings/fnc_formatElapsedTime.sqf
Labels: Bug Fix

#1449 Remove Feature And Enhancement Request Templates
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Enhancement

#1453 Use execVM for all unit tests
  addons/arrays/test.sqf
  addons/common/test.sqf
  addons/common/test_config.sqf
  addons/common/test_inventory.sqf
  addons/common/test_ret.sqf
  addons/common/test_weaponComponents.sqf
  addons/diagnostic/fnc_test.sqf
  addons/diagnostic/test.sqf
  addons/events/test.sqf
  addons/hashes/test.sqf
  addons/jr/test.sqf
  addons/main/test.sqf
  addons/network/test.sqf
  addons/network/test_network.sqf
  addons/strings/test.sqf
  addons/vectors/test.sqf
Labels: Enhancement, Tools

#1454 Fix shuffle test
  addons/arrays/test_shuffle.sqf
Labels: Cleanup, Tools

#1455 Make Attachment Swap Close Item Action Menu
  addons/accessory/XEH_preInit.sqf
Labels: Bug Fix

#1452 Common - Remove editor init fix
  addons/common/Cfg3DEN.hpp
  addons/main/script_mod.hpp
Labels: Cleanup

#1457 Replace "Community Base Addons -" by "CBA" in the `Network` menu
  addons/network/stringtable.xml
Labels: Cleanup
