Repository CBATeam/CBA_A3, pull requests merged in 2021-12, with the labels that each got.

#1516 Add support for encoding and decoding JSON with hash maps
  addons/hashes/fnc_encodeJSON.sqf
  addons/hashes/fnc_parseJSON.sqf
  addons/hashes/test_parseJSON.sqf
Labels: Feature

#1524 Update Mikero Tools to public version released 2021-11-06
  .github/workflows/pboproject.yml
  tools/make.py
Labels: Tools, Ignore Changelog

#1508 Add bipod support for accessory/switchAttachment to header info
  addons/accessory/fnc_switchAttachment.sqf
Labels: Enhancement

#1525 XEH - Fix issues with Western Sahara
  addons/xeh/CfgVehicles.hpp
Labels: Task

#1507 Common - Add support for commander turrets to `cba_common_fnc_turretDir`
  addons/common/fnc_turretDir.sqf
Labels: Enhancement

#1515 Fix nil throwing errors in scheduled environment
  addons/hashes/fnc_encodeJSON.sqf
Labels: Bug Fix

#1523 prevent switching accessory while in Zeus
  addons/accessory/fnc_switchAttachment.sqf
Labels: Bug Fix
