Repository CBATeam/CBA_A3, pull requests merged in 2021-02, with the labels that each got.

#1416 Pylint fixes for build.py
  tools/build.py
Labels: Enhancement, Ignore Changelog, Tools

#1417 check_strings: Pylint fixes
  tools/check_strings.py
Labels: Enhancement, Ignore Changelog, Tools

#1415 Remove use of __EVAL macro
  addons/ui/RscDisplayOptionsLayout.hpp
Labels: Ignore Changelog, Tools

#1419 Use configOf command
  addons/common/fnc_getObjectConfig.sqf
  addons/common/fnc_isTurnedOut.sqf
  addons/common/fnc_randomizeFacewear.sqf
  addons/disposable/fnc_replaceMagazineCargo.sqf
  addons/main/script_mod.hpp
  addons/optics/fnc_currentOptic.sqf
  addons/xeh/fnc_initEvents.sqf
Labels: Enhancement

#1418 config_style_checker: Pylint fixes
  tools/config_style_checker.py
Labels: Enhancement, Ignore Changelog, Tools

#1421 Events - Prep userKeyHandler at preStart
  addons/events/XEH_preStart.sqf
Labels: Ignore Changelog

#1318 Misc configs fixes for Hemtt
  addons/events/config.cpp
  addons/settings/gui.hpp
Labels: Ignore Changelog

#1410 Use fileExists command (2.02)
  addons/main/script_macros_common.hpp
Labels: 2.02, Enhancement

#1376 Utilize isNotEqualTo
  addons/accessory/fnc_switchAttachment.sqf
  addons/ai/fnc_clearWaypoints.sqf
  addons/ai/fnc_searchNearby.sqf
  addons/ai/fnc_taskDefend.sqf
  addons/common/fnc_getArea.sqf
  addons/common/fnc_headDir.sqf
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
  addons/events/fnc_addMarkerEventHandler.sqf
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
  addons/events/fnc_removeEventHandler.sqf
  addons/events/fnc_userKeyHandler.sqf
  addons/hashes/fnc_parseJSON.sqf
  addons/keybinding/fnc_addKeybind.sqf
  addons/keybinding/fnc_initDisplayConfigure.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_updateOpticInfo.sqf
  addons/settings/XEH_postInit.sqf
  addons/settings/fnc_export.sqf
  addons/settings/fnc_gui_settingCheckbox.sqf
  addons/settings/fnc_gui_settingColor.sqf
  addons/settings/fnc_gui_settingEditbox.sqf
  addons/settings/fnc_gui_settingList.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
  addons/settings/fnc_gui_settingSlider.sqf
  addons/settings/fnc_gui_settingTime.sqf
  addons/settings/fnc_gui_sourceChanged.sqf
  addons/settings/fnc_initDisplay3DEN.sqf
  addons/statemachine/fnc_clockwork.sqf
  addons/strings/fnc_formatNumber.sqf
  addons/ui/fnc_addItemContextMenuOption.sqf
  addons/ui/test_preload.sqf
  addons/versioning/XEH_preInit.sqf
  addons/xeh/fnc_compileEventHandlers.sqf
  addons/xeh/fnc_initDisplay.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
  addons/xeh/fnc_startFallbackLoop.sqf
Labels: 2.02, Enhancement

#1420 XEH - Fix missing XEH on AoW objects (2.02)
  addons/common/config.cpp
  addons/main/script_mod.hpp
  addons/xeh/CfgVehicles.hpp
Labels: 2.02, Bug Fix

#1426 XEH - Fix missing XEH on GM objects
  addons/xeh/CfgVehicles.hpp
Labels: Bug Fix, Needs Testing

#1427 XEH - Add Suppressed EH from 2.02
  addons/xeh/script_component.hpp
  addons/xeh/script_xeh.hpp
Labels: 2.02, Feature
