Repository CBATeam/CBA_A3, pull requests merged in 2021-06, with the labels that each got.

#1460 Fix CBA_fnc_turretDir for certain UAV turrets
  addons/common/fnc_turretDir.sqf
Labels: Bug Fix

#1450 Add sqfc support
  .gitignore
  addons/accessory/CfgEventHandlers.hpp
  addons/characters/CfgEventHandlers.hpp
  addons/common/CfgEventHandlers.hpp
  addons/diagnostic/CfgEventHandlers.hpp
  addons/disposable/CfgEventHandlers.hpp
  addons/events/CfgEventHandlers.hpp
  addons/help/CfgEventhandlers.hpp
  addons/keybinding/CfgEventHandlers.hpp
  addons/main/script_macros_common.hpp
  addons/network/CfgEventHandlers.hpp
  addons/optics/CfgEventHandlers.hpp
  addons/settings/CfgEventHandlers.hpp
  addons/statemachine/CfgEventHandlers.hpp
  addons/ui/CfgEventHandlers.hpp
  addons/vectors/CfgEventHandlers.hpp
  addons/versioning/CfgEventHandlers.hpp
  hemtt.toml
  sqfc.json
  tools/compile_sqf.py
Labels: Enhancement

#1194 Add Lobby Manager
  addons/ui/CfgFunctions.hpp
  addons/ui/Display3DEN.hpp
  addons/ui/LobbyManager.hpp
  addons/ui/RscTitles.hpp
  addons/ui/arrow_down_ca.paa
  addons/ui/arrow_up_ca.paa
  addons/ui/config.cpp
  addons/ui/fnc_initDisplayMultiplayerSetup.sqf
  addons/ui/fnc_openLobbyManager.sqf
  addons/ui/script_component.hpp
  addons/ui/stringtable.xml
Labels: Feature

#1461 Lobby Manager - Always use maximum available space for warning label
  addons/ui/LobbyManager.hpp
  addons/ui/fnc_openLobbyManager.sqf
Labels: Enhancement

#1462 Translation - Add French Translation (Lobby Manager)
  addons/ui/stringtable.xml
Labels: Translation

#1464 Consolidate settings into a single category
  addons/diagnostic/initSettings.sqf
  addons/diagnostic/stringtable.xml
  addons/disposable/initSettings.sqf
  addons/events/initSettings.sqf
  addons/main/stringtable.xml
  addons/network/initSettings.sqf
  addons/network/stringtable.xml
  addons/optics/initSettings.sqf
  addons/optics/stringtable.xml
  addons/ui/initSettings.sqf
  addons/ui/stringtable.xml
Labels: Cleanup

#1465 Add Empty Resolution LOD To Invisible Targets
  addons/ai/InvisibleTarget.p3d
  addons/ai/InvisibleTargetVehicle.p3d
Labels: Bug Fix

#1466 Detect SOG Cinematic module camera in feature camera
  addons/common/XEH_preInit.sqf
  addons/common/fnc_getActiveFeatureCamera.sqf
Labels: Enhancement

#1468 Replace some Compile preprocessFile/LineNumbers with compileScript
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
  addons/ui/test_preload.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
Labels: Enhancement

#1471 Fix Callsign Attribute Compatibility
  addons/common/Cfg3DEN.hpp
Labels: Bug Fix
