Repository CBATeam/CBA_A3, pull requests merged in 2021-03, with the labels that each got.

#1406 Add naked unit bug workaround
  addons/network/CfgEventHandlers.hpp
  addons/network/XEH_preInit.sqf
  addons/network/config.cpp
  addons/network/initSettings.sqf
  addons/network/stringtable.xml
Labels: Feature

#1422 XEH - Use compileScript in CBA_fnc_compileFunction
  addons/xeh/fnc_compileFunction.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
Labels: 2.02

#1434 Release Drafter - Fix case sensitivity
  .github/release-drafter.yml
Labels: Ignore Changelog

#1441 Fix alt+tab causing issues with indentation insert on tab press
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
Labels: Bug Fix
