Repository CBATeam/CBA_A3, pull requests merged in 2021-01, with the labels that each got.

#1403 Tools - Update make.py and build.py for change to mikro
  addons/ee/$NOBIN$
  tools/build.py
  tools/make.py
Labels: Ignore Changelog, Tools

#1380 Use unitTurret command
  addons/common/fnc_turretPath.sqf
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
Labels: Cleanup

#1407 Add function to get standard deviation (CBA_fnc_standardDeviation)
  addons/arrays/CfgFunctions.hpp
  addons/arrays/fnc_standardDeviation.sqf
  addons/arrays/test.sqf
  addons/arrays/test_standardDeviation.sqf
Labels: Feature

#1398 Joint Rails - Add Compatibility With Mk14 Classic variant
  addons/jr/CfgWeapons.hpp
Labels: Bug Fix

#1344 Unlock malaria-infected civs
  addons/characters/$PBOPREFIX$
  addons/characters/CfgEditorSubcategories.hpp
  addons/characters/CfgEventHandlers.hpp
  addons/characters/CfgFaces.hpp
  addons/characters/CfgVehicles.hpp
  addons/characters/XEH_preInit.sqf
  addons/characters/config.cpp
  addons/characters/script_component.hpp
  addons/characters/stringtable.xml
Labels: Feature

#1409 CharSick - Only add XEH on server
  addons/characters/XEH_preInit.sqf
Labels: Ignore Changelog

#1357 Diagnostics - Add indentation in debug console with Tab
  addons/diagnostic/XEH_preInit.sqf
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
  addons/diagnostic/initSettings.sqf
  addons/diagnostic/script_component.hpp
  addons/diagnostic/stringtable.xml
Labels: Enhancement
