Repository CBATeam/CBA_A3, pull requests merged in 2021-09, with the labels that each got.

#1498 Fix XEH issues with GM 1.4 patch
  addons/xeh/CfgVehicles.hpp
Labels: Enhancement

#1489 Accessory - Removes action from pointers while not in slot
  addons/accessory/XEH_preInit.sqf
Labels: Bug Fix

#1500 Set REQUIRED_VERSION to 2.06
  addons/main/script_mod.hpp
Labels: Ignore Changelog

#1497 Fix CBA_fnc_removeMagazineCargo for ground containers
  addons/common/fnc_removeMagazineCargo.sqf
Labels: Bug Fix

#1491 Tools - Make SQFC, update /include
  include/a3/ui_f/hpp/defineCommonColors.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineDIKCodes.inc
  include/a3/ui_f/hpp/defineResincl.inc
  tools/make.py
  tools/updateIncludes.py
Labels: Tools, Ignore Changelog
