Repository CBATeam/CBA_A3, pull requests merged in 2022-05, with the labels that each got.

#1543 Czech stringtables
  addons/ai/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
Labels: Translation

#1546 Keybinding - Sort subcategories using localized names
  addons/keybinding/fnc_gui_update.sqf
Labels: Bug Fix

#1547 AI - Add basic delay for `CBA_fnc_searchNearby` while loop
  addons/ai/fnc_searchNearby.sqf
Labels: Bug Fix

#1503 Extended Loadout Framework
  addons/loadout/$PBOPREFIX$
  addons/loadout/CfgEventHandlers.hpp
  addons/loadout/CfgFunctions.hpp
  addons/loadout/XEH_preInit.sqf
  addons/loadout/config.cpp
  addons/loadout/fnc_getLoadout.sqf
  addons/loadout/fnc_setLoadout.sqf
  addons/loadout/script_component.hpp
Labels: Feature

#1548 Fix bug in CBA_fnc_setLoadout
  addons/loadout/fnc_setLoadout.sqf
Labels: Bug Fix
