Repository CBATeam/CBA_A3, pull requests merged in 2022-03, with the labels that each got.

#1530 UI - Fix context menu item tooltip
  addons/ui/fnc_openItemContextMenu.sqf
Labels: Bug Fix

#1533 Add CBA_fnc_weekDay
  addons/common/CfgFunctions.hpp
  addons/common/fnc_weekDay.sqf
  addons/common/test.sqf
  addons/common/test_common.sqf
Labels: Feature

#1536 UI - Show `worldname` as tooltip for maps on mission select
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Enhancement

#1528 CBA_fnc_canAddItem for vehicles and crates
  addons/common/fnc_canAddItem.sqf
Labels: Enhancement

#1527 Common - improve CBA_fnc_addMagazine and CBA_fnc_addMagazineCargo
  addons/common/fnc_addMagazine.sqf
  addons/common/fnc_addMagazineCargo.sqf
Labels: Enhancement
