Repository CBATeam/CBA_A3, pull requests merged in 2023-12, with the labels that each got.

#1631 ci: Update 7zip function to extract game data
  .github/workflows/pboproject.yml
Labels: Bug Fix, Tools, Ignore Changelog

#1629 Translations - Update Japanese
  addons/ai/stringtable.xml
  addons/characters/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/network/stringtable.xml
  addons/settings/stringtable.xml
  addons/ui/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Translation

#1628 Translations - Add Spanish
  addons/ai/stringtable.xml
Labels: Translation

#1633 Tools - Add `requiredVersion` to all sub configs
  addons/accessory/MRT_AccFncs/config.cpp
  addons/jr/asdg_jointmuzzles/config.cpp
  addons/jr/asdg_jointrails/config.cpp
  addons/ui/ui_helper/config.cpp
  addons/xeh/CBA_Extended_EventHandlers/config.cpp
  addons/xeh/Extended_EventHandlers/config.cpp
  addons/xeh/ee/config.cpp
  addons/xeh/xeh_a3/config.cpp
Labels: Enhancement, Tools
