Repository CBATeam/CBA_A3, pull requests merged in 2023-10, with the labels that each got.

#1612 Joint Rails - Fix `_typefilter` undefined variable error
  addons/jr/fnc_compatibleItems.sqf
Labels: Bug Fix, Ignore Changelog

#1537 Add magazine wells for VN CDLC
  addons/jam/jam_vn/CfgMagazineWells.hpp
  addons/jam/jam_vn/CfgWeapons.hpp
  addons/jam/jam_vn/config.cpp
  addons/jam/jam_vn/script_component.hpp
Labels: Enhancement, 2.14

#1618 Arrays - Fix number bounds (ASC compatibility)
  addons/arrays/fnc_selectBest.sqf
Labels: Bug Fix, Ignore Changelog

#1604 Update magazine wells for SPE CDLC
  addons/jam/jam_spe/CfgWeapons.hpp
Labels: Enhancement, 2.14

#1617 Settings - Add "volatile" option to not persist server settings after restart
  .hemtt/project.toml
  addons/settings/fnc_clear.sqf
  addons/settings/fnc_gui_sourceChanged.sqf
  addons/settings/fnc_init.sqf
  addons/settings/fnc_set.sqf
  addons/settings/gui.hpp
  addons/settings/initSettings.sqf
  addons/settings/script_component.hpp
  addons/settings/stringtable.xml
  template/cba_settings_userconfig/config.cpp
Labels: Enhancement

#1623 CI - Update actions/checkout to v4 and remove release drafter description
  .github/release-drafter.yml
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
  .github/workflows/pboproject.yml
Labels: Tools, Ignore Changelog
