Repository CBATeam/CBA_A3, pull requests merged in 2023-09, with the labels that each got.

#1588 XEH - Add more events
  addons/xeh/CfgEventHandlers.hpp
  addons/xeh/script_component.hpp
  addons/xeh/script_xeh.hpp
Labels: Enhancement

#1580 Fix JSON parsing function of numerals formatted as scientific notation with uppercase E
  addons/hashes/fnc_parseJSON.sqf
Labels: Bug Fix

#1590 Optimize CBA_fnc_compileFinal for Arma 2.14
  addons/common/fnc_compileFinal.sqf
Labels: Enhancement, 2.14

#1589 XEH - Move compats to individual addons
  .github/workflows/pboproject.yml
  addons/ee/$PBOPREFIX$
  addons/ee/config.cpp
  addons/ee/script_component.hpp
  addons/main/script_mod.hpp
  addons/xeh/CfgVehicles.hpp
  addons/xeh/compat_contact/config.cpp
  addons/xeh/compat_csla/config.cpp
  addons/xeh/compat_sog/config.cpp
  addons/xeh/compat_ws/config.cpp
  addons/xeh/ee/config.cpp
  tools/make.py
Labels: Cleanup

#1595 Accessory - Add conditional blocking of switchable attachments
  addons/accessory/CfgFunctions.hpp
  addons/accessory/XEH_preInit.sqf
  addons/accessory/fnc_addAttachmentCondition.sqf
  addons/accessory/fnc_switchAttachment.sqf
  addons/accessory/fnc_switchableAttachments.sqf
Labels: Enhancement

#1557 Common - Optimize and expand `CBA_fnc_addWeaponWithoutItems`
  addons/common/fnc_addWeaponWithoutItems.sqf
Labels: Enhancement

#1558 Joint Rails - Optimize `CBA_fnc_compatibleItems`
  addons/jr/fnc_compatibleItems.sqf
Labels: Enhancement

#1585 Common - Optimize `CBA_fnc_compatibleMagazines`
  addons/common/fnc_compatibleMagazines.sqf
Labels: Enhancement

#1581 Setting - Added multiline setting parsing support
  addons/settings/fnc_parse.sqf
Labels: Enhancement

#1486 Item Context Menu - Change option selection to Single click instead of Double click
  addons/ui/fnc_openItemContextMenu.sqf
Labels: Enhancement

#1599 General - Relative `script_component.hpp` includes
  addons/jam/jam_finish/script_component.hpp
  addons/jr/jr_prep/script_component.hpp
  addons/ui/flexiMenu/data/menu_arma2.hpp
  addons/ui/flexiMenu/data/menu_buttonList.hpp
  addons/ui/flexiMenu/data/menu_iconRow.hpp
  addons/ui/flexiMenu/data/menu_popup.hpp
  addons/ui/flexiMenu/data/menu_rose.hpp
  addons/ui/flexiMenu/fnc_add.sqf
  addons/ui/flexiMenu/fnc_execute.sqf
  addons/ui/flexiMenu/fnc_getMenuDef.sqf
  addons/ui/flexiMenu/fnc_getMenuOption.sqf
  addons/ui/flexiMenu/fnc_keyDown.sqf
  addons/ui/flexiMenu/fnc_keyUp.sqf
  addons/ui/flexiMenu/fnc_list.sqf
  addons/ui/flexiMenu/fnc_menu.sqf
  addons/ui/flexiMenu/fnc_menuShortcut.sqf
  addons/ui/flexiMenu/fnc_mouseButtonDown.sqf
  addons/ui/flexiMenu/fnc_openMenuByDef.sqf
  addons/ui/flexiMenu/fnc_remove.sqf
  addons/ui/flexiMenu/fnc_setObjectMenuSource.sqf
  addons/ui/flexiMenu/init.sqf
  addons/xeh/xeh_a3/config.cpp
  addons/xeh/xeh_a3/script_component.hpp
  addons/xeh/xeh_contact/script_component.hpp
  addons/xeh/xeh_csla/script_component.hpp
  addons/xeh/xeh_sog/script_component.hpp
  addons/xeh/xeh_ws/script_component.hpp
  optionals/legacy_jr/legacy_jr_prep/script_component.hpp
Labels: Enhancement, Ignore Changelog

#1600 Tools - Update SQF and Config Validators from ACE3
  addons/main/script_macros_common.hpp
  addons/modules/CfgVehicles.hpp
  addons/ui/flexiMenu/data/menu_popup.hpp
  optionals/cache_disable/script_component.hpp
  optionals/diagnostic_enable_logging/script_component.hpp
  optionals/disable_missing_mod_check/script_component.hpp
  tools/config_style_checker.py
  tools/sqf_validator.py
  tools/updateIncludes.py
Labels: Enhancement, Tools, Ignore Changelog

#1540 Add magazine wells for CSLA CDLC
  addons/jam/jam_csla/CfgMagazineWells.hpp
  addons/jam/jam_csla/CfgWeapons.hpp
  addons/jam/jam_csla/config.cpp
  addons/jam/jam_csla/script_component.hpp
Labels: Enhancement, 2.14

#1538 Add magazine wells for GM CDLC
  addons/jam/jam_gm/CfgMagazineWells.hpp
  addons/jam/jam_gm/CfgWeapons.hpp
  addons/jam/jam_gm/config.cpp
  addons/jam/jam_gm/script_component.hpp
Labels: Enhancement, 2.14

#1597 Add magazine wells for SPE CDLC
  addons/jam/jam_spe/CfgMagazineWells.hpp
  addons/jam/jam_spe/CfgWeapons.hpp
  addons/jam/jam_spe/config.cpp
  addons/jam/jam_spe/script_component.hpp
Labels: Enhancement, 2.14

#1603 Update magazine wells for CSLA CDLC
  addons/jam/jam_csla/CfgMagazineWells.hpp
  addons/jam/jam_csla/CfgWeapons.hpp
Labels: Enhancement, Bug Fix, Ignore Changelog

#1539 Add magazine wells for WS CDLC
  addons/jam/jam_ws/CfgMagazineWells.hpp
  addons/jam/jam_ws/CfgWeapons.hpp
  addons/jam/jam_ws/config.cpp
  addons/jam/jam_ws/script_component.hpp
Labels: Enhancement, 2.14

#1608 Common - SUBCSTRING/LSUBLSTRING Macros
  addons/main/script_macros_common.hpp
Labels: Enhancement

#1605 Update magazine wells for GM CDLC
  addons/jam/jam_gm/CfgWeapons.hpp
Labels: Enhancement, Ignore Changelog, 2.14

#1609 Tools - Fix configs for HEMTT v1.9.0
  addons/ui/flexiMenu/data/menu_arma2.hpp
  addons/ui/flexiMenu/data/menu_buttonList.hpp
  addons/ui/flexiMenu/data/menu_iconRow.hpp
  addons/ui/flexiMenu/data/menu_popup.hpp
  addons/ui/flexiMenu/data/menu_rose.hpp
  include/a3/ui_f/hpp/defineResincl.inc
Labels: Tools, Ignore Changelog

#1610 Korean translation updated
  addons/settings/stringtable.xml
Labels: Translation

#1614 Common - Fix `CBA_fnc_getTerrainProfile` macro
  addons/common/fnc_getTerrainProfile.sqf
Labels: Bug Fix

#1615 Tools - Exclude "test_" sqfs from asc
  .hemtt/project.toml
  sqfc.json
Labels: Ignore Changelog
