Repository CBATeam/CBA_A3, pull requests merged in 2023-06, with the labels that each got.

#1571 Main - Fix `script_macros_mission` redefinitions
  addons/main/script_macros_mission.hpp
Labels: Bug Fix

#1568 Optics - Increase width of hidePeripheralVision slightly to prevent gaps
  addons/optics/fnc_initDisplayInterrupt.sqf
  addons/optics/fnc_loadScriptedOptic.sqf
Labels: Bug Fix

#1566 Common - Fix debug macros in CBA_fnc_switchPlayer
  addons/common/fnc_switchPlayer.sqf
Labels: Bug Fix

#1492 Item Context Menu - Flexible menu width
  addons/ui/fnc_openItemContextMenu.sqf
  addons/ui/script_component.hpp
Labels: Bug Fix

#1556 Common - Updated CBA_fnc_removeBinocularMagazine
  addons/common/fnc_removeBinocularMagazine.sqf
Labels: Cleanup

#1555 Common - Updated CBA_fnc_binocularMagazine
  addons/common/fnc_binocularMagazine.sqf
Labels: Cleanup

#1522 Add CBA_fnc_prettyFormat
  addons/strings/CfgFunctions.hpp
  addons/strings/fnc_prettyFormat.sqf
  addons/strings/script_component.hpp
  addons/strings/test.sqf
  addons/strings/test_prettyFormat.sqf
Labels: Feature
