Repository CBATeam/CBA_A3, pull requests merged in 2024-11, with the labels that each got.

#1706 Common - Cleanup DEFAULT_PARAM, _this
  addons/ai/fnc_taskPatrol.sqf
  addons/common/fnc_directCall.sqf
  addons/common/fnc_getTerrainProfile.sqf
  addons/diagnostic/XEH_preInit.sqf
  addons/diagnostic/fnc_test.sqf
  addons/diagnostic/test_parameters.inc.sqf
  addons/main/script_macros_common.hpp
  addons/ui/fnc_notify.sqf
  addons/ui/fnc_openItemContextMenu.sqf
  addons/xeh/fnc_init.sqf
  addons/xeh/fnc_postInit.sqf
Labels: Cleanup

#1701 Common - Use `objectParent` for vehicle detection (HEMTT L-S18)
  .hemtt/lints.toml
  addons/common/fnc_canUseWeapon.sqf
  addons/common/fnc_deleteEntity.sqf
  addons/common/fnc_getUnitAnim.sqf
  addons/common/fnc_getUnitDeathAnim.sqf
Labels: Cleanup

#1710 Common - Update `FUNC(addBinocularMagazine)`
  addons/common/fnc_addBinocularMagazine.sqf
Labels: Enhancement

#1711 waitUntilAndExecute - Fixes missleading description
  addons/common/fnc_waitUntilAndExecute.sqf
Labels: Cleanup

#1717 Tools - Update all stringtables
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/arrays/stringtable.xml
  addons/characters/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/disposable/stringtable.xml
  addons/events/stringtable.xml
  addons/hashes/stringtable.xml
  addons/help/stringtable.xml
  addons/jam/stringtable.xml
  addons/jr/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/music/stringtable.xml
  addons/network/stringtable.xml
  addons/optics/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/strings/stringtable.xml
  addons/ui/stringtable.xml
  addons/vectors/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Ignore Changelog

#1716 Common - Optimize `CBA_fnc_createMarker`
  addons/common/fnc_createMarker.sqf
Labels: Enhancement

#1709 JAM - Add additional magwells and fix a couple bugs
  addons/jam/CfgMagazineWells.hpp
  addons/jam/magwells_338LM.hpp
  addons/jam/magwells_357Mag.hpp
  addons/jam/magwells_357SIG.hpp
  addons/jam/magwells_40SW.hpp
  addons/jam/magwells_40mm.hpp
  addons/jam/magwells_45ACP.hpp
  addons/jam/magwells_762x39.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1719 Fix XEH `initPost`
  addons/ui/fnc_openItemContextMenu.sqf
  addons/xeh/fnc_init.sqf
Labels: Bug Fix, Ignore Changelog
