Repository CBATeam/CBA_A3, pull requests merged in 2024-08, with the labels that each got.

#1677 Common - Update `CBA_fnc_selectWeapon`
  addons/common/fnc_selectWeapon.sqf
Labels: Enhancement

#1662 Disposable - Updated `cba_disposable_fnc_replaceMagazineCargo`
  addons/disposable/XEH_preInit.sqf
  addons/disposable/fnc_replaceMagazineCargo.sqf
Labels: Bug Fix

#1680 Settings - Fix comment removal and deleting // in strings when not wanted
  addons/settings/fnc_import.sqf
  addons/settings/fnc_parse.sqf
  addons/settings/test_parse.sqf
  addons/settings/test_settings_comments.inc.sqf
  addons/settings/test_settings_strings.inc.sqf
Labels: Bug Fix

#1663 Disposable - Use native hashmaps
  addons/disposable/XEH_preInit.sqf
  addons/disposable/fnc_changeDisposableLauncherClass.sqf
  addons/disposable/fnc_firedDisposable.sqf
  addons/disposable/fnc_initDisplayInventory.sqf
  addons/disposable/fnc_replaceMagazineCargo.sqf
Labels: Enhancement

#1670 Events - Add `CBA_fnc_addBISPlayerEventHandler` for adding EHs to just the player (from ACE3)
  addons/events/CfgFunctions.hpp
  addons/events/fnc_addBISPlayerEventHandler.sqf
  addons/events/fnc_removeBISPlayerEventHandler.sqf
Labels: Enhancement

#1683 Network - Update component name
  addons/network/stringtable.xml
Labels: Cleanup

#1684 Help - Sort addons, credits and keybindings alphabetically
  addons/help/XEH_postInit.sqf
  addons/help/XEH_preInit.sqf
  addons/help/XEH_preStart.sqf
Labels: Bug Fix, Cleanup

#1685 Common - Fix a format in test macro
  addons/common/test_weaponComponents.sqf
Labels: Ignore Changelog
