Repository CBATeam/CBA_A3, pull requests merged in 2024-10, with the labels that each got.

#1695 UI - Show mission filename as tooltip for missions on mission select
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Feature, Add To Changelog

#1675 AI - Update fnc_addWaypoint Header
  addons/ai/fnc_addWaypoint.sqf
Labels: Cleanup

#1702 ci: Mikero Tools 2024-10-11
  .github/workflows/pboproject.yml
  tools/make.py
Labels: Tools

#1704 UI - Fix undefined unit variable for context menu
  addons/ui/fnc_openItemContextMenu.sqf
Labels: Bug Fix

#1692 Common - Add color conversion functions
  addons/common/CfgFunctions.hpp
  addons/common/XEH_preInit.sqf
  addons/common/XEH_preStart.sqf
  addons/common/fnc_colorAHEXtoDecimal.sqf
  addons/common/fnc_colorARGBtoDecimal.sqf
  addons/common/fnc_colorHEXAtoDecimal.sqf
  addons/common/fnc_colorHEXtoDecimal.sqf
  addons/common/fnc_colorRGBAtoDecimal.sqf
  addons/common/fnc_colorRGBtoDecimal.sqf
  addons/common/fnc_cssColorToDecimal.sqf
  addons/common/fnc_cssColorToHEX.sqf
  addons/common/fnc_cssColorToTexture.sqf
Labels: Enhancement

#1698 Add some lint annotations
  addons/common/fnc_directCall.sqf
  addons/common/init_perFrameHandler.sqf
  addons/common/test.sqf
  addons/common/test_ret.inc.sqf
  addons/hashes/fnc_parseYAML.sqf
  addons/versioning/fnc_version_check.sqf
Labels: Ignore Changelog
