Repository CBATeam/CBA_A3, pull requests merged in 2024-04, with the labels that each got.

#1656 JAM - Add MP35 magwell
  addons/jam/magwells_9x19.hpp
Labels: Enhancement

#1654 Translate - French
  addons/diagnostic/stringtable.xml
  addons/settings/stringtable.xml
  optionals/legacy_jr/stringtable.xml
Labels: Translation

#1655 Joint Rails - Fix `CBA_fnc_compatibleItems` undefined variable
  addons/jr/fnc_compatibleItems.sqf
Labels: Bug Fix

#1657 JAM - Fix incorrect magwells on some SPE CDLC weapons
  addons/jam/jam_spe/CfgWeapons.hpp
Labels: Bug Fix
