Repository CBATeam/CBA_A3, pull requests merged in 2024-09, with the labels that each got.

#1687 General - Fix command casing
  addons/accessory/fnc_addAttachmentCondition.sqf
  addons/accessory/fnc_switchAttachment.sqf
  addons/accessory/fnc_switchableAttachments.sqf
  addons/ai/fnc_addWaypoint.sqf
  addons/ai/fnc_searchNearby.sqf
  addons/ai/fnc_taskDefend.sqf
  addons/arrays/fnc_shuffle.sqf
  addons/common/fnc_deleteEntity.sqf
  addons/common/fnc_execNextFrame.sqf
  addons/common/fnc_getTerrainProfile.sqf
  addons/common/fnc_isAlive.sqf
  addons/common/fnc_turretDir.sqf
  addons/common/fnc_weaponComponents.sqf
  addons/common/init_addMiscItemsToArsenal.sqf
  addons/common/init_perFrameHandler.sqf
  addons/common/test_macro_is_x.sqf
  addons/diagnostic/fnc_initExtendedDebugConsole.sqf
  addons/help/XEH_preStart.sqf
  addons/keybinding/fnc_registerKeybind.sqf
  addons/music/fnc_compileMusic.sqf
  addons/music/fnc_findMusic.sqf
  addons/music/fnc_playMusic.sqf
  addons/optics/RscInGameUI.hpp
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/optics/fnc_initDisplayInterrupt.sqf
  addons/optics/fnc_loadScriptedOptic.sqf
  addons/optics/script_component.hpp
  addons/settings/script_component.hpp
  addons/ui/RscTitles.hpp
  addons/ui/flexiMenu/fnc_getMenuOption.sqf
  addons/ui/flexiMenu/fnc_list.sqf
  addons/ui/flexiMenu/fnc_menu.sqf
  addons/ui/fnc_initDisplayInterrupt.sqf
  addons/ui/fnc_initDisplayPassword.sqf
  addons/ui/fnc_initDisplayRemoteMissions.sqf
  addons/ui/fnc_notify.sqf
  addons/ui/fnc_openItemContextMenu.sqf
  addons/ui/script_component.hpp
  include/a3/functions_f/debug/fn_isDebugConsoleAllowed.sqf
  include/a3/functions_f/gui/fn_initDisplay.sqf
  include/a3/functions_f/misc/fn_endLoadingScreen.sqf
  include/a3/functions_f/misc/fn_startLoadingScreen.sqf
Labels: Cleanup

#1688 CI - Fix HEMTT artifacts not uploaded
  .github/workflows/arma.yml
Labels: Tools, Ignore Changelog

#1329 Item Rename Framework
  addons/ui/CfgFunctions.hpp
  addons/ui/XEH_preInit.sqf
  addons/ui/XEH_preStart.sqf
  addons/ui/fnc_getInventoryItemData.sqf
  addons/ui/fnc_initDisplayInventory.sqf
  addons/ui/fnc_renameInventoryItem.sqf
Labels: Feature

#1682 Disposables - Fix check if floating point mass are roughly the same
  addons/disposable/XEH_preInit.sqf
Labels: Ignore Changelog

#1679 Optics - Optimize `Fired` EH to use `CBA_fnc_addBISPlayerEventHandler`
  addons/optics/XEH_preInit.sqf
Labels: Enhancement

#1691 Korean translation minor updated
  addons/diagnostic/stringtable.xml
  addons/jr/stringtable.xml
Labels: Translation

#1693 Settings - Add missing setting type to header & wiki additions
  addons/settings/fnc_addSetting.sqf
  addons/settings/fnc_init.sqf
Labels: Cleanup, Add To Changelog
