Repository CBATeam/CBA_A3, pull requests merged in 2024-03, with the labels that each got.

#1647 General - Cleanup warnings for HEMTT
  addons/accessory/fnc_addAttachmentCondition.sqf
  addons/ai/fnc_taskDefend.sqf
  addons/ai/fnc_taskSearchArea.sqf
  addons/common/fnc_addPlayerAction.sqf
  addons/common/init_addMiscItemsToArsenal.sqf
  addons/common/test_config.sqf
  addons/common/test_position.sqf
  addons/disposable/XEH_preInit.sqf
  addons/events/fnc_mouseWheelHandler.sqf
  addons/jr/fnc_compatibleItems.sqf
  addons/music/fnc_getMusicData.sqf
  addons/optics/fnc_animateScriptedOptic.sqf
  addons/settings/fnc_gui_settingOverwrite.sqf
  addons/settings/fnc_set.sqf
  addons/settings/test_parse.sqf
  addons/settings/test_settings_comments.inc.sqf
  addons/settings/test_settings_comments_eof.inc.sqf
  addons/settings/test_settings_multiline.inc.sqf
  addons/settings/test_settings_regular.inc.sqf
  addons/settings/test_settings_strings.inc.sqf
  addons/settings/test_settings_unicode.inc.sqf
  addons/strings/fnc_prettyFormat.sqf
  addons/strings/test_strings.sqf
  addons/ui/flexiMenu/fnc_add.sqf
  addons/ui/flexiMenu/fnc_execute.sqf
  addons/ui/flexiMenu/fnc_getMenuDef.sqf
  addons/ui/flexiMenu/fnc_getMenuOption.sqf
  addons/ui/flexiMenu/fnc_keyDown.sqf
  addons/ui/flexiMenu/fnc_list.sqf
  addons/ui/flexiMenu/fnc_menu.sqf
  addons/ui/flexiMenu/fnc_mouseButtonDown.sqf
  addons/ui/flexiMenu/fnc_openMenuByDef.sqf
  addons/ui/flexiMenu/fnc_remove.sqf
  addons/ui/fnc_getFov.sqf
  addons/vectors/test_vectors.sqf
  addons/versioning/XEH_postInit.sqf
  addons/versioning/XEH_postInitClient.sqf
  addons/versioning/fnc_version_check.sqf
  addons/xeh/fnc_addClassEventHandler.sqf
  addons/xeh/fnc_compileEventHandlers.sqf
  addons/xeh/fnc_initDisplay3DEN.sqf
  addons/xeh/fnc_isRecompileEnabled.sqf
  addons/xeh/fnc_preInit.sqf
  addons/xeh/fnc_preStart.sqf
  addons/xeh/script_component.hpp
Labels: Cleanup

#1643 Loadout - Add CBA_preLoadoutSet event
  addons/loadout/fnc_setLoadout.sqf
Labels: Enhancement

#1634 Tools - Don't compile 4 funcs that modify base functions
  .hemtt/project.toml
  addons/diagnostic/CfgFunctions.hpp
  addons/diagnostic/fnc_isDebugConsoleAllowed.inc.sqf
  addons/xeh/CfgFunctions.hpp
  addons/xeh/fnc_endLoadingScreen.inc.sqf
  addons/xeh/fnc_initDisplay.inc.sqf
  addons/xeh/fnc_startLoadingScreen.inc.sqf
  sqfc.json
Labels: Tools

#1640 Common - Add CBA_fnc_escapeRegex
  addons/common/CfgFunctions.hpp
  addons/common/fnc_escapeRegex.sqf
Labels: Feature

#1644 JAM - Add FRF2, Hecate 2, Sterling, and 22mm NATO Spigot magwells
  addons/jam/CfgMagazineWells.hpp
  addons/jam/magwells_22mm.hpp
  addons/jam/magwells_50BMG.hpp
  addons/jam/magwells_762x51.hpp
  addons/jam/magwells_9x19.hpp
Labels: Enhancement, 2.16

#1651 UI - Improve support of pictures in mission list filter
  addons/ui/fnc_initDisplayRemoteMissions.sqf
Labels: Enhancement

#1650 Common - Improve remove magazine functions
  addons/common/fnc_removeMagazine.sqf
  addons/common/fnc_removeMagazineCargo.sqf
  addons/common/test_inventory.sqf
Labels: Enhancement

#1601 JAM - Add dev tool to diagnose mags added via wells
  addons/jam/dev_diagnoseMagWells.sqf
Labels: Tools, Ignore Changelog
