Repository CBATeam/CBA_A3, pull requests merged in 2024-07, with the labels that each got.

#1674 Common - Fix typo in `fnc_uniqueUnitItems`
  addons/common/fnc_uniqueUnitItems.sqf
Labels: Ignore Changelog

#1669 Events - Update player event loop to use new UAV AI getter
  addons/events/fnc_playerEvent.sqf
  addons/main/script_mod.hpp
Labels: Enhancement

#1668 Disposable - Throw errors for invalid config entries for disposable launchers
  addons/disposable/XEH_preInit.sqf
Labels: Enhancement

#1664 Disposable - Fix magazines not being replaced by their disposable counterparts
  addons/disposable/fnc_replaceMagazineCargo.sqf
Labels: Bug Fix

#1676 Common - Make `CBA_fnc_getMuzzles` configcase
  addons/common/fnc_getMuzzles.sqf
Labels: Enhancement

#1673 Common - Fix `CBA_fnc_canAddItem` when item mass is 0
  addons/common/fnc_canAddItem.sqf
Labels: Bug Fix

#1665 Events - Add "turretOpticsMode" Player EH
  addons/events/fnc_addPlayerEventHandler.sqf
  addons/events/fnc_playerEvent.sqf
Labels: Enhancement
