Repository CBATeam/CBA_A3, pull requests merged in 2025-02, with the labels that each got.

#1728 CSLA Compats - Update for CSLA 1.2
  addons/jam/jam_csla/CfgWeapons.hpp
  addons/xeh/xeh_csla/CfgVehicles.hpp
Labels: Cleanup

#1727 XEH - Disable `MagazineUnloaded` EH to prevent crash to desktop
  addons/xeh/CfgEventHandlers.hpp
  addons/xeh/script_component.hpp
  addons/xeh/script_xeh.hpp
Labels: Bug

#1726 UI - Add password fill compatiblity for "connectToServer" (2.19+)
  addons/ui/fnc_initDisplayPassword.sqf
Labels: Enhancement

#1722 Update globalSay and globalSay3D to use CBA events
  addons/network/CfgEventHandlers.hpp
  addons/network/CfgFunctions.hpp
  addons/network/XEH_postInit.sqf
  addons/network/fnc_globalSay.sqf
  addons/network/fnc_globalSay3D.sqf
Labels: Enhancement

#1724 Add Bitwise Functions
  addons/bitwise/$PBOPREFIX$
  addons/bitwise/CfgFunctions.hpp
  addons/bitwise/config.cpp
  addons/bitwise/fnc_bitflagsCheck.sqf
  addons/bitwise/fnc_bitflagsCheckBool.sqf
  addons/bitwise/fnc_bitflagsFlip.sqf
  addons/bitwise/fnc_bitflagsSet.sqf
  addons/bitwise/fnc_bitflagsUnset.sqf
  addons/bitwise/fnc_bitwiseAND.sqf
  addons/bitwise/fnc_bitwiseLROT.sqf
  addons/bitwise/fnc_bitwiseLSHFT.sqf
  addons/bitwise/fnc_bitwiseNOT.sqf
  addons/bitwise/fnc_bitwiseOR.sqf
  addons/bitwise/fnc_bitwiseRROT.sqf
  addons/bitwise/fnc_bitwiseRSHFT.sqf
  addons/bitwise/fnc_bitwiseXOR.sqf
  addons/bitwise/fnc_logBase2.sqf
  addons/bitwise/script_component.hpp
Labels: Enhancement

#1730 Joint Rails - Add GM compat
  addons/jr/CfgWeapons.hpp
  addons/jr/compat_gm/config.cpp
  addons/jr/compat_gm/jr_classes.hpp
  addons/jr/compat_gm/script_component.hpp
  addons/jr/jr_classes.hpp
Labels: Enhancement

#1732 Bitwise - minor style fix
  addons/bitwise/$PBOPREFIX$
  addons/bitwise/CfgFunctions.hpp
  addons/bitwise/config.cpp
  addons/bitwise/fnc_bitflagsCheck.sqf
  addons/bitwise/fnc_bitflagsCheckBool.sqf
  addons/bitwise/fnc_bitflagsFlip.sqf
  addons/bitwise/fnc_bitflagsSet.sqf
  addons/bitwise/fnc_bitwiseAND.sqf
  addons/bitwise/fnc_bitwiseLROT.sqf
  addons/bitwise/fnc_bitwiseLSHFT.sqf
  addons/bitwise/fnc_bitwiseNOT.sqf
  addons/bitwise/fnc_bitwiseOR.sqf
  addons/bitwise/fnc_bitwiseRROT.sqf
  addons/bitwise/fnc_bitwiseRSHFT.sqf
  addons/bitwise/fnc_bitwiseXOR.sqf
  addons/bitwise/fnc_logBase2.sqf
  addons/bitwise/script_component.hpp
Labels: Ignore Changelog

#1725 Update fnc_Say3dglobal - avoid issue with _distance and _params as Array
  addons/network/fnc_globalSay3D.sqf
Labels: Cleanup

#1649 Added: QTE Framework
  addons/main/config.cpp
  addons/quicktime/$PBOPREFIX$
  addons/quicktime/CfgEventHandlers.hpp
  addons/quicktime/CfgFunctions.hpp
  addons/quicktime/XEH_preInit.sqf
  addons/quicktime/config.cpp
  addons/quicktime/fnc_generateQTESequence.sqf
  addons/quicktime/fnc_getFormattedQTESequence.sqf
  addons/quicktime/fnc_keyPressedQTE.sqf
  addons/quicktime/fnc_runQTE.sqf
  addons/quicktime/initSettings.inc.sqf
  addons/quicktime/script_component.hpp
  addons/quicktime/stringtable.xml
Labels: Feature

#1733 bitwise - add missing component name and sort qt strings
  addons/bitwise/stringtable.xml
  addons/quicktime/stringtable.xml
Labels: Ignore Changelog

#1734 Update scope check from 2 to 1 on magazine add/remove functions
  addons/common/fnc_addMagazine.sqf
  addons/common/fnc_addMagazineCargo.sqf
  addons/common/fnc_removeMagazine.sqf
  addons/common/fnc_removeMagazineCargo.sqf
Labels: Bug Fix

#1736 quicktime - fix undefined maxDistance
  .hemtt/lints.toml
  addons/quicktime/fnc_runQTE.sqf
Labels: Bug Fix, Ignore Changelog
