Repository CBATeam/CBA_A3, pull requests merged in 2025-06, with the labels that each got.

#1762 JAM/GM - Fix SVD using PM-63 mags
  addons/jam/jam_gm/CfgWeapons.hpp
Labels: Bug Fix

#1761 Common - Fix items being dropped on ground if unit is too heavy for `CBA_fnc_addItem`
  addons/common/fnc_addItem.sqf
Labels: Bug Fix

#1760 XEH - Fix GM XEH changes
  addons/xeh/CfgVehicles.hpp
Labels: Bug Fix

#1764 Common - Add `_skipAnim` parameter to `CBA_fnc_addItem` and related functions
  addons/common/fnc_addItem.sqf
  addons/common/fnc_addMagazine.sqf
  addons/common/fnc_addWeapon.sqf
  addons/common/fnc_dropMagazine.sqf
  addons/common/fnc_dropWeapon.sqf
Labels: Enhancement

#1769 Diagnostic - Fix UBC
  addons/diagnostic/gui.hpp
Labels: Ignore Changelog

#1767 JAM - Add 2.20 illumination flares to magwell
  addons/jam/magwells_40mm.hpp
  addons/main/script_macros_common.hpp
  addons/main/script_mod.hpp
Labels: Bug Fix, BI's Fault

#1770 Diagnostic - cleanup unused watchControls
  addons/diagnostic/gui.hpp
Labels: Ignore Changelog

#1756 Settings - Handle mismatched setting category capitalization
  addons/settings/XEH_preInit.sqf
  addons/settings/fnc_initDisplayGameOptions.sqf
Labels: Bug Fix

#1772 Translations - Fix Russian
  addons/accessory/stringtable.xml
  addons/ai/stringtable.xml
  addons/bitwise/stringtable.xml
  addons/characters/stringtable.xml
  addons/common/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/keybinding/stringtable.xml
  addons/main/stringtable.xml
  addons/modules/stringtable.xml
  addons/network/stringtable.xml
  addons/optics/stringtable.xml
  addons/quicktime/stringtable.xml
  addons/settings/stringtable.xml
  addons/statemachine/stringtable.xml
  addons/ui/stringtable.xml
  addons/versioning/stringtable.xml
  addons/xeh/stringtable.xml
Labels: Translation

#1778 Fix creating category settings
  addons/settings/gui_createCategory.inc.sqf
Labels: Bug Fix

#1779 Settings - Fix setting showing up in unicode subcategories
  addons/settings/XEH_preInit.sqf
  addons/settings/gui_createCategory.inc.sqf
Labels: Bug Fix
