Repository CBATeam/CBA_A3, pull requests merged in 2025-03, with the labels that each got.

#1737 Translations - Update Japanese
  addons/bitwise/stringtable.xml
  addons/quicktime/stringtable.xml
Labels: Translation

#1738 Translations - Add German
  addons/bitwise/stringtable.xml
  addons/diagnostic/stringtable.xml
  addons/quicktime/stringtable.xml
  addons/settings/stringtable.xml
Labels: Translation

#1739 Translations - Update French
  addons/bitwise/stringtable.xml
  addons/quicktime/stringtable.xml
Labels: Translation

#1740 Arrays - Optimise `CBA_fnc_getArrayElements`
  addons/arrays/fnc_getArrayElements.sqf
Labels: Enhancement

#1744 QTE - Fix length off-by-one
  addons/quicktime/fnc_generateQTESequence.sqf
Labels: Bug Fix

#1745 Translations - Fix typo in Japanese
  addons/quicktime/stringtable.xml
Labels: Translation

#1746 Quicktime - Replace unicode arrows and add information about reset
  addons/quicktime/XEH_preInit.sqf
  addons/quicktime/fnc_generateQTESequence.sqf
  addons/quicktime/fnc_getFormattedQTESequence.sqf
  addons/quicktime/fnc_keyPressedQTE.sqf
  addons/quicktime/fnc_runQTE.sqf
Labels: Enhancement

#1747 Quicktime - Minor cleanup
  addons/quicktime/fnc_keyPressedQTE.sqf
  addons/quicktime/fnc_runQTE.sqf
Labels: Cleanup

#1749 UI - Fix `CBA_fnc_notify` script error
  addons/ui/fnc_notify.sqf
Labels: Bug Fix

#1748 General - Use `select -1`
  addons/common/fnc_getMagazineIndex.sqf
  addons/events/XEH_preInit.sqf
  addons/hashes/fnc_parseYAML.sqf
Labels: Enhancement

#1752 Translations - updated Czech translation
  addons/characters/stringtable.xml
  addons/network/stringtable.xml
  addons/quicktime/stringtable.xml
  addons/settings/stringtable.xml
Labels: Translation
